/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionLogin;
    QAction *actionLogout;
    QAction *actionLock;
    QAction *actionDatabases;
    QAction *actionPreferences;
    QAction *actionExit;
    QAction *actionHelp;
    QAction *actionAbout;
    QAction *actionRoomChart;
    QAction *actionRoom_list;
    QAction *actionDaily_movement;
    QAction *actionGuest_file;
    QAction *actionReservatios;
    QAction *actionContacts;
    QAction *actionUsers;
    QAction *actionUsers_groups;
    QAction *actionRoom_view;
    QAction *actionInvoices;
    QAction *actionNew_reservation;
    QAction *actionPartners;
    QAction *actionHakk;
    QAction *actionTables;
    QAction *actionNames_of_menu;
    QAction *actionMain_partitions_of_menu;
    QAction *actionType_of_dishes;
    QAction *actionDishes;
    QAction *actionModifiers;
    QAction *actionStorages;
    QAction *actionMenu_review;
    QAction *actionPrinters;
    QAction *actionTrack_changes;
    QAction *actionCredit_card;
    QAction *actionCity_Ledger_balance;
    QAction *actionChange_password;
    QAction *actionNew_advance_entry;
    QAction *actionGlobal_config;
    QAction *actionComplex_dish;
    QAction *actionCategories;
    QAction *actionType_of_bed;
    QAction *actionSynchronization;
    QAction *actionRestaurant;
    QAction *actionCategory_to_sell;
    QAction *actionCity_Ledger;
    QAction *actionCurrencies;
    QAction *actionForecast_Occupancy_Category;
    QAction *actionMonthly_Report;
    QAction *actionSetup_Tax_Printer;
    QAction *actionInvoice_items;
    QAction *actionIn_house_guest;
    QAction *actionExpected_arrivals;
    QAction *actionRecheckout;
    QAction *actionPosting_charge;
    QAction *actionDiscount;
    QAction *actionRe_checkin;
    QAction *actionTransfer_amount;
    QAction *actionExpected_arrivals_simple;
    QAction *action;
    QAction *actionCash_report_total;
    QAction *actionUpdate_program;
    QAction *actionReceipt_vaucher;
    QAction *actionCity_Ledger_detailed_balance;
    QAction *actionCash_repoort_detailed;
    QAction *actionVauchers;
    QAction *actionNotes;
    QAction *actionCall_history;
    QAction *actionEvent;
    QAction *actionDaily_financial_report;
    QAction *actionBanquet_comment;
    QAction *actionCity_ledger_balance_2;
    QAction *actionHistory_of_calls;
    QAction *actionCardex_analysis;
    QAction *actionExport_invoices;
    QAction *actionComplimentary_comment;
    QAction *actionExport_active_reservations;
    QAction *actionReport_buillder;
    QAction *actionRemarks;
    QAction *actionHotel_status;
    QAction *actionList_of_source_reservation;
    QAction *actionYearly_financial_report;
    QAction *actionReports_set;
    QAction *actionStatistics;
    QAction *actionUtils;
    QAction *actionExport_data;
    QAction *actionAdvance_report;
    QAction *actionRestaurant_online;
    QAction *actionReservation_groups;
    QAction *actionConfigure_Welcome_Page;
    QAction *actionPartners_group;
    QAction *actionGuest_titles;
    QAction *actionNationality_file;
    QAction *actionCheckout_invoices_free_rooming;
    QAction *actionNew_group_reservation;
    QAction *actionChanges_of_states_of_room;
    QAction *actionCanceled_reservations;
    QAction *actionWeb;
    QAction *actionStorehouse;
    QAction *actionNew_store_document;
    QAction *actionMaterials_list;
    QAction *actionReservations_by_date_created;
    QAction *actionPartners_2;
    QAction *actionDocuments_list;
    QAction *actionMaterials_in_the_store;
    QAction *actionStore_movement;
    QAction *actionCoupons;
    QAction *actionCalculate_output_of_restaurant;
    QAction *actionExport_back;
    QAction *actionOpen_breakfast;
    QAction *actionMonthly_occupancy_percentages;
    QAction *actionNaitonality_report_by_period;
    QAction *actionCancelation_No_show_fees;
    QAction *actionCancelation_No_show_fee;
    QAction *actionSales_by_storages;
    QAction *actionGuest_by_nationality;
    QAction *actionModels_of_cars;
    QAction *actionCostumers_cars;
    QAction *actionReport_by_payment;
    QAction *actionPartners_debts;
    QAction *actionCoupons_sales;
    QAction *actionCoupons_seria;
    QAction *actionAccounts;
    QAction *actionAccounts_2;
    QAction *actionStore_entries;
    QAction *actionNew_store_checkpoint;
    QAction *actionPartner_payments;
    QAction *actionCoupons_statistics;
    QAction *actionDebts;
    QAction *actionBreakfast_report;
    QAction *actionDiscount_report;
    QAction *actionSales_report_by_cars;
    QAction *actionDiscount_total;
    QAction *actionCostumers;
    QAction *actionRefund_voucher;
    QAction *actionRoom_inventory;
    QAction *actionCity_ledger_advance;
    QAction *actionTransfer_CL_amount;
    QAction *actionAvailable_amounts;
    QAction *actionGuest_Tray_Ledger;
    QAction *actionIn_house_detailed_balance;
    QAction *actionAvaiable_rooms;
    QAction *actionRoom_inventory_2;
    QAction *actionRoom_inventory_states;
    QAction *actionList_of_checkin_guests;
    QAction *actionLenght_of_stay;
    QAction *actionExport_reservations;
    QAction *actionExecute_failed_sql;
    QAction *actionT_report;
    QAction *actionDisable_second_database;
    QAction *actionRoom_arrangement;
    QAction *actionRoom_assignment;
    QAction *actionWakeup_calls;
    QAction *actionDaily_transactions;
    QAction *actionHotel_hierarchy;
    QAction *actionNew_room_chart;
    QAction *actionCall_rates;
    QAction *actionTemporary_receipts;
    QAction *actionExpected_arrivals_departures_2;
    QAction *actionGuest_Tray_Ledger_By_Date;
    QAction *actionRecover_invoice;
    QAction *actionPosting_charge_2;
    QAction *actionTransfer_log;
    QAction *actionQuick_reservations;
    QAction *actionTax_server;
    QAction *actionQuick_checkout;
    QAction *actionCash_report_items;
    QAction *actionPrint_tax_of_checkout_invoices;
    QAction *actionOptions;
    QAction *actionInhouse_guest_future;
    QAction *actionForecast_occupancy_by_category;
    QAction *actionState_of_the_room;
    QAction *actionExpected_departures_simple;
    QAction *actionExpected_arivals_simple;
    QAction *actionArmSoft;
    QAction *actionFiscal_report;
    QAction *actionUpload_menu_from_FrontDesk;
    QAction *actionReceipt_voucher;
    QAction *actionCategory_statistics;
    QWidget *centralWidget;
    QHBoxLayout *horizontalLayout;
    QTabWidget *tabWidget;
    QMenuBar *menuBar;
    QMenu *menuWorking;
    QMenu *menuReservation;
    QMenu *menuAbout;
    QMenu *menuReports;
    QMenu *menuDirectory;
    QMenu *menuApplication;
    QMenu *menuPreferences;
    QMenu *menuRestaurant;
    QMenu *menuCity_ledger_advance;
    QMenu *menuReception;
    QMenu *menuCachier;
    QMenu *menuAnalytics;
    QMenu *menuOther_Reports;
    QMenu *menuRestaurant_2;
    QMenu *menuStorehouse;
    QMenu *menuDiscount_system;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1375, 596);
        MainWindow->setMouseTracking(true);
        actionLogin = new QAction(MainWindow);
        actionLogin->setObjectName(QString::fromUtf8("actionLogin"));
        actionLogout = new QAction(MainWindow);
        actionLogout->setObjectName(QString::fromUtf8("actionLogout"));
        actionLock = new QAction(MainWindow);
        actionLock->setObjectName(QString::fromUtf8("actionLock"));
        actionDatabases = new QAction(MainWindow);
        actionDatabases->setObjectName(QString::fromUtf8("actionDatabases"));
        actionPreferences = new QAction(MainWindow);
        actionPreferences->setObjectName(QString::fromUtf8("actionPreferences"));
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        actionHelp = new QAction(MainWindow);
        actionHelp->setObjectName(QString::fromUtf8("actionHelp"));
        actionAbout = new QAction(MainWindow);
        actionAbout->setObjectName(QString::fromUtf8("actionAbout"));
        actionRoomChart = new QAction(MainWindow);
        actionRoomChart->setObjectName(QString::fromUtf8("actionRoomChart"));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/images/analytics.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRoomChart->setIcon(icon);
        actionRoom_list = new QAction(MainWindow);
        actionRoom_list->setObjectName(QString::fromUtf8("actionRoom_list"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/images/room-key.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRoom_list->setIcon(icon1);
        actionDaily_movement = new QAction(MainWindow);
        actionDaily_movement->setObjectName(QString::fromUtf8("actionDaily_movement"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/images/graph.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDaily_movement->setIcon(icon2);
        actionGuest_file = new QAction(MainWindow);
        actionGuest_file->setObjectName(QString::fromUtf8("actionGuest_file"));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/images/guests.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionGuest_file->setIcon(icon3);
        actionReservatios = new QAction(MainWindow);
        actionReservatios->setObjectName(QString::fromUtf8("actionReservatios"));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/images/bed.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionReservatios->setIcon(icon4);
        actionContacts = new QAction(MainWindow);
        actionContacts->setObjectName(QString::fromUtf8("actionContacts"));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/images/phone.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionContacts->setIcon(icon5);
        actionUsers = new QAction(MainWindow);
        actionUsers->setObjectName(QString::fromUtf8("actionUsers"));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/images/boy.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionUsers->setIcon(icon6);
        actionUsers_groups = new QAction(MainWindow);
        actionUsers_groups->setObjectName(QString::fromUtf8("actionUsers_groups"));
        actionUsers_groups->setIcon(icon3);
        actionRoom_view = new QAction(MainWindow);
        actionRoom_view->setObjectName(QString::fromUtf8("actionRoom_view"));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/images/window.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRoom_view->setIcon(icon7);
        actionInvoices = new QAction(MainWindow);
        actionInvoices->setObjectName(QString::fromUtf8("actionInvoices"));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/images/invoice.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionInvoices->setIcon(icon8);
        actionNew_reservation = new QAction(MainWindow);
        actionNew_reservation->setObjectName(QString::fromUtf8("actionNew_reservation"));
        actionNew_reservation->setIcon(icon1);
        actionPartners = new QAction(MainWindow);
        actionPartners->setObjectName(QString::fromUtf8("actionPartners"));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/images/partner.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionPartners->setIcon(icon9);
        actionHakk = new QAction(MainWindow);
        actionHakk->setObjectName(QString::fromUtf8("actionHakk"));
        actionTables = new QAction(MainWindow);
        actionTables->setObjectName(QString::fromUtf8("actionTables"));
        actionNames_of_menu = new QAction(MainWindow);
        actionNames_of_menu->setObjectName(QString::fromUtf8("actionNames_of_menu"));
        actionMain_partitions_of_menu = new QAction(MainWindow);
        actionMain_partitions_of_menu->setObjectName(QString::fromUtf8("actionMain_partitions_of_menu"));
        actionType_of_dishes = new QAction(MainWindow);
        actionType_of_dishes->setObjectName(QString::fromUtf8("actionType_of_dishes"));
        actionDishes = new QAction(MainWindow);
        actionDishes->setObjectName(QString::fromUtf8("actionDishes"));
        actionModifiers = new QAction(MainWindow);
        actionModifiers->setObjectName(QString::fromUtf8("actionModifiers"));
        actionStorages = new QAction(MainWindow);
        actionStorages->setObjectName(QString::fromUtf8("actionStorages"));
        actionMenu_review = new QAction(MainWindow);
        actionMenu_review->setObjectName(QString::fromUtf8("actionMenu_review"));
        actionPrinters = new QAction(MainWindow);
        actionPrinters->setObjectName(QString::fromUtf8("actionPrinters"));
        actionTrack_changes = new QAction(MainWindow);
        actionTrack_changes->setObjectName(QString::fromUtf8("actionTrack_changes"));
        QIcon icon10;
        icon10.addFile(QString::fromUtf8(":/images/tracking.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionTrack_changes->setIcon(icon10);
        actionCredit_card = new QAction(MainWindow);
        actionCredit_card->setObjectName(QString::fromUtf8("actionCredit_card"));
        QIcon icon11;
        icon11.addFile(QString::fromUtf8(":/images/credit-card.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCredit_card->setIcon(icon11);
        actionCity_Ledger_balance = new QAction(MainWindow);
        actionCity_Ledger_balance->setObjectName(QString::fromUtf8("actionCity_Ledger_balance"));
        actionChange_password = new QAction(MainWindow);
        actionChange_password->setObjectName(QString::fromUtf8("actionChange_password"));
        actionNew_advance_entry = new QAction(MainWindow);
        actionNew_advance_entry->setObjectName(QString::fromUtf8("actionNew_advance_entry"));
        actionGlobal_config = new QAction(MainWindow);
        actionGlobal_config->setObjectName(QString::fromUtf8("actionGlobal_config"));
        QIcon icon12;
        icon12.addFile(QString::fromUtf8(":/images/settings.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionGlobal_config->setIcon(icon12);
        actionComplex_dish = new QAction(MainWindow);
        actionComplex_dish->setObjectName(QString::fromUtf8("actionComplex_dish"));
        actionCategories = new QAction(MainWindow);
        actionCategories->setObjectName(QString::fromUtf8("actionCategories"));
        QIcon icon13;
        icon13.addFile(QString::fromUtf8(":/images/category.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCategories->setIcon(icon13);
        actionType_of_bed = new QAction(MainWindow);
        actionType_of_bed->setObjectName(QString::fromUtf8("actionType_of_bed"));
        actionType_of_bed->setIcon(icon4);
        actionSynchronization = new QAction(MainWindow);
        actionSynchronization->setObjectName(QString::fromUtf8("actionSynchronization"));
        QIcon icon14;
        icon14.addFile(QString::fromUtf8(":/images/database.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSynchronization->setIcon(icon14);
        actionRestaurant = new QAction(MainWindow);
        actionRestaurant->setObjectName(QString::fromUtf8("actionRestaurant"));
        QIcon icon15;
        icon15.addFile(QString::fromUtf8(":/images/cutlery.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRestaurant->setIcon(icon15);
        actionCategory_to_sell = new QAction(MainWindow);
        actionCategory_to_sell->setObjectName(QString::fromUtf8("actionCategory_to_sell"));
        actionCity_Ledger = new QAction(MainWindow);
        actionCity_Ledger->setObjectName(QString::fromUtf8("actionCity_Ledger"));
        actionCity_Ledger->setIcon(icon9);
        actionCurrencies = new QAction(MainWindow);
        actionCurrencies->setObjectName(QString::fromUtf8("actionCurrencies"));
        actionForecast_Occupancy_Category = new QAction(MainWindow);
        actionForecast_Occupancy_Category->setObjectName(QString::fromUtf8("actionForecast_Occupancy_Category"));
        actionMonthly_Report = new QAction(MainWindow);
        actionMonthly_Report->setObjectName(QString::fromUtf8("actionMonthly_Report"));
        actionMonthly_Report->setIcon(icon2);
        actionSetup_Tax_Printer = new QAction(MainWindow);
        actionSetup_Tax_Printer->setObjectName(QString::fromUtf8("actionSetup_Tax_Printer"));
        QIcon icon16;
        icon16.addFile(QString::fromUtf8(":/images/tax.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSetup_Tax_Printer->setIcon(icon16);
        actionInvoice_items = new QAction(MainWindow);
        actionInvoice_items->setObjectName(QString::fromUtf8("actionInvoice_items"));
        QIcon icon17;
        icon17.addFile(QString::fromUtf8(":/images/list.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionInvoice_items->setIcon(icon17);
        actionIn_house_guest = new QAction(MainWindow);
        actionIn_house_guest->setObjectName(QString::fromUtf8("actionIn_house_guest"));
        actionIn_house_guest->setIcon(icon4);
        actionExpected_arrivals = new QAction(MainWindow);
        actionExpected_arrivals->setObjectName(QString::fromUtf8("actionExpected_arrivals"));
        QIcon icon18;
        icon18.addFile(QString::fromUtf8(":/images/arrival.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionExpected_arrivals->setIcon(icon18);
        actionRecheckout = new QAction(MainWindow);
        actionRecheckout->setObjectName(QString::fromUtf8("actionRecheckout"));
        QIcon icon19;
        icon19.addFile(QString::fromUtf8(":/images/goto.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRecheckout->setIcon(icon19);
        actionPosting_charge = new QAction(MainWindow);
        actionPosting_charge->setObjectName(QString::fromUtf8("actionPosting_charge"));
        actionDiscount = new QAction(MainWindow);
        actionDiscount->setObjectName(QString::fromUtf8("actionDiscount"));
        actionRe_checkin = new QAction(MainWindow);
        actionRe_checkin->setObjectName(QString::fromUtf8("actionRe_checkin"));
        actionRe_checkin->setIcon(icon4);
        actionTransfer_amount = new QAction(MainWindow);
        actionTransfer_amount->setObjectName(QString::fromUtf8("actionTransfer_amount"));
        actionExpected_arrivals_simple = new QAction(MainWindow);
        actionExpected_arrivals_simple->setObjectName(QString::fromUtf8("actionExpected_arrivals_simple"));
        actionExpected_arrivals_simple->setIcon(icon18);
        action = new QAction(MainWindow);
        action->setObjectName(QString::fromUtf8("action"));
        actionCash_report_total = new QAction(MainWindow);
        actionCash_report_total->setObjectName(QString::fromUtf8("actionCash_report_total"));
        actionUpdate_program = new QAction(MainWindow);
        actionUpdate_program->setObjectName(QString::fromUtf8("actionUpdate_program"));
        actionReceipt_vaucher = new QAction(MainWindow);
        actionReceipt_vaucher->setObjectName(QString::fromUtf8("actionReceipt_vaucher"));
        actionCity_Ledger_detailed_balance = new QAction(MainWindow);
        actionCity_Ledger_detailed_balance->setObjectName(QString::fromUtf8("actionCity_Ledger_detailed_balance"));
        actionCash_repoort_detailed = new QAction(MainWindow);
        actionCash_repoort_detailed->setObjectName(QString::fromUtf8("actionCash_repoort_detailed"));
        actionVauchers = new QAction(MainWindow);
        actionVauchers->setObjectName(QString::fromUtf8("actionVauchers"));
        QIcon icon20;
        icon20.addFile(QString::fromUtf8(":/images/file.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionVauchers->setIcon(icon20);
        actionNotes = new QAction(MainWindow);
        actionNotes->setObjectName(QString::fromUtf8("actionNotes"));
        QIcon icon21;
        icon21.addFile(QString::fromUtf8(":/images/notepad.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionNotes->setIcon(icon21);
        actionCall_history = new QAction(MainWindow);
        actionCall_history->setObjectName(QString::fromUtf8("actionCall_history"));
        QIcon icon22;
        icon22.addFile(QString::fromUtf8(":/images/phone-call.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCall_history->setIcon(icon22);
        actionEvent = new QAction(MainWindow);
        actionEvent->setObjectName(QString::fromUtf8("actionEvent"));
        QIcon icon23;
        icon23.addFile(QString::fromUtf8(":/images/banket.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionEvent->setIcon(icon23);
        actionDaily_financial_report = new QAction(MainWindow);
        actionDaily_financial_report->setObjectName(QString::fromUtf8("actionDaily_financial_report"));
        actionDaily_financial_report->setIcon(icon2);
        actionBanquet_comment = new QAction(MainWindow);
        actionBanquet_comment->setObjectName(QString::fromUtf8("actionBanquet_comment"));
        actionCity_ledger_balance_2 = new QAction(MainWindow);
        actionCity_ledger_balance_2->setObjectName(QString::fromUtf8("actionCity_ledger_balance_2"));
        actionHistory_of_calls = new QAction(MainWindow);
        actionHistory_of_calls->setObjectName(QString::fromUtf8("actionHistory_of_calls"));
        actionHistory_of_calls->setIcon(icon22);
        actionCardex_analysis = new QAction(MainWindow);
        actionCardex_analysis->setObjectName(QString::fromUtf8("actionCardex_analysis"));
        actionCardex_analysis->setIcon(icon9);
        actionExport_invoices = new QAction(MainWindow);
        actionExport_invoices->setObjectName(QString::fromUtf8("actionExport_invoices"));
        actionExport_invoices->setIcon(icon14);
        actionComplimentary_comment = new QAction(MainWindow);
        actionComplimentary_comment->setObjectName(QString::fromUtf8("actionComplimentary_comment"));
        actionExport_active_reservations = new QAction(MainWindow);
        actionExport_active_reservations->setObjectName(QString::fromUtf8("actionExport_active_reservations"));
        actionExport_active_reservations->setIcon(icon14);
        actionReport_buillder = new QAction(MainWindow);
        actionReport_buillder->setObjectName(QString::fromUtf8("actionReport_buillder"));
        QIcon icon24;
        icon24.addFile(QString::fromUtf8(":/images/reports.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionReport_buillder->setIcon(icon24);
        actionRemarks = new QAction(MainWindow);
        actionRemarks->setObjectName(QString::fromUtf8("actionRemarks"));
        QIcon icon25;
        icon25.addFile(QString::fromUtf8(":/images/remarks.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRemarks->setIcon(icon25);
        actionHotel_status = new QAction(MainWindow);
        actionHotel_status->setObjectName(QString::fromUtf8("actionHotel_status"));
        QIcon icon26;
        icon26.addFile(QString::fromUtf8(":/images/info.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionHotel_status->setIcon(icon26);
        actionList_of_source_reservation = new QAction(MainWindow);
        actionList_of_source_reservation->setObjectName(QString::fromUtf8("actionList_of_source_reservation"));
        actionYearly_financial_report = new QAction(MainWindow);
        actionYearly_financial_report->setObjectName(QString::fromUtf8("actionYearly_financial_report"));
        actionYearly_financial_report->setIcon(icon2);
        actionReports_set = new QAction(MainWindow);
        actionReports_set->setObjectName(QString::fromUtf8("actionReports_set"));
        actionReports_set->setIcon(icon24);
        actionStatistics = new QAction(MainWindow);
        actionStatistics->setObjectName(QString::fromUtf8("actionStatistics"));
        actionStatistics->setIcon(icon24);
        actionUtils = new QAction(MainWindow);
        actionUtils->setObjectName(QString::fromUtf8("actionUtils"));
        actionUtils->setIcon(icon12);
        actionExport_data = new QAction(MainWindow);
        actionExport_data->setObjectName(QString::fromUtf8("actionExport_data"));
        actionExport_data->setIcon(icon14);
        actionAdvance_report = new QAction(MainWindow);
        actionAdvance_report->setObjectName(QString::fromUtf8("actionAdvance_report"));
        actionRestaurant_online = new QAction(MainWindow);
        actionRestaurant_online->setObjectName(QString::fromUtf8("actionRestaurant_online"));
        QIcon icon27;
        icon27.addFile(QString::fromUtf8(":/images/openedorder.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRestaurant_online->setIcon(icon27);
        actionReservation_groups = new QAction(MainWindow);
        actionReservation_groups->setObjectName(QString::fromUtf8("actionReservation_groups"));
        actionReservation_groups->setIcon(icon4);
        actionConfigure_Welcome_Page = new QAction(MainWindow);
        actionConfigure_Welcome_Page->setObjectName(QString::fromUtf8("actionConfigure_Welcome_Page"));
        actionPartners_group = new QAction(MainWindow);
        actionPartners_group->setObjectName(QString::fromUtf8("actionPartners_group"));
        actionPartners_group->setIcon(icon9);
        actionGuest_titles = new QAction(MainWindow);
        actionGuest_titles->setObjectName(QString::fromUtf8("actionGuest_titles"));
        actionGuest_titles->setIcon(icon3);
        actionNationality_file = new QAction(MainWindow);
        actionNationality_file->setObjectName(QString::fromUtf8("actionNationality_file"));
        actionNationality_file->setIcon(icon3);
        actionCheckout_invoices_free_rooming = new QAction(MainWindow);
        actionCheckout_invoices_free_rooming->setObjectName(QString::fromUtf8("actionCheckout_invoices_free_rooming"));
        actionCheckout_invoices_free_rooming->setIcon(icon8);
        actionNew_group_reservation = new QAction(MainWindow);
        actionNew_group_reservation->setObjectName(QString::fromUtf8("actionNew_group_reservation"));
        actionNew_group_reservation->setIcon(icon1);
        actionChanges_of_states_of_room = new QAction(MainWindow);
        actionChanges_of_states_of_room->setObjectName(QString::fromUtf8("actionChanges_of_states_of_room"));
        actionCanceled_reservations = new QAction(MainWindow);
        actionCanceled_reservations->setObjectName(QString::fromUtf8("actionCanceled_reservations"));
        QIcon icon28;
        icon28.addFile(QString::fromUtf8(":/images/garbage.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCanceled_reservations->setIcon(icon28);
        actionWeb = new QAction(MainWindow);
        actionWeb->setObjectName(QString::fromUtf8("actionWeb"));
        QIcon icon29;
        icon29.addFile(QString::fromUtf8(":/images/internet.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionWeb->setIcon(icon29);
        actionStorehouse = new QAction(MainWindow);
        actionStorehouse->setObjectName(QString::fromUtf8("actionStorehouse"));
        actionNew_store_document = new QAction(MainWindow);
        actionNew_store_document->setObjectName(QString::fromUtf8("actionNew_store_document"));
        actionNew_store_document->setEnabled(true);
        QIcon icon30;
        icon30.addFile(QString::fromUtf8(":/images/storage.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionNew_store_document->setIcon(icon30);
        actionMaterials_list = new QAction(MainWindow);
        actionMaterials_list->setObjectName(QString::fromUtf8("actionMaterials_list"));
        actionReservations_by_date_created = new QAction(MainWindow);
        actionReservations_by_date_created->setObjectName(QString::fromUtf8("actionReservations_by_date_created"));
        actionReservations_by_date_created->setIcon(icon4);
        actionPartners_2 = new QAction(MainWindow);
        actionPartners_2->setObjectName(QString::fromUtf8("actionPartners_2"));
        actionPartners_2->setIcon(icon9);
        actionDocuments_list = new QAction(MainWindow);
        actionDocuments_list->setObjectName(QString::fromUtf8("actionDocuments_list"));
        actionMaterials_in_the_store = new QAction(MainWindow);
        actionMaterials_in_the_store->setObjectName(QString::fromUtf8("actionMaterials_in_the_store"));
        actionStore_movement = new QAction(MainWindow);
        actionStore_movement->setObjectName(QString::fromUtf8("actionStore_movement"));
        actionCoupons = new QAction(MainWindow);
        actionCoupons->setObjectName(QString::fromUtf8("actionCoupons"));
        QIcon icon31;
        icon31.addFile(QString::fromUtf8(":/images/discount.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCoupons->setIcon(icon31);
        actionCalculate_output_of_restaurant = new QAction(MainWindow);
        actionCalculate_output_of_restaurant->setObjectName(QString::fromUtf8("actionCalculate_output_of_restaurant"));
        QIcon icon32;
        icon32.addFile(QString::fromUtf8(":/images/calculator.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCalculate_output_of_restaurant->setIcon(icon32);
        actionExport_back = new QAction(MainWindow);
        actionExport_back->setObjectName(QString::fromUtf8("actionExport_back"));
        actionExport_back->setIcon(icon14);
        actionOpen_breakfast = new QAction(MainWindow);
        actionOpen_breakfast->setObjectName(QString::fromUtf8("actionOpen_breakfast"));
        QIcon icon33;
        icon33.addFile(QString::fromUtf8(":/images/dinner.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionOpen_breakfast->setIcon(icon33);
        actionMonthly_occupancy_percentages = new QAction(MainWindow);
        actionMonthly_occupancy_percentages->setObjectName(QString::fromUtf8("actionMonthly_occupancy_percentages"));
        actionMonthly_occupancy_percentages->setIcon(icon24);
        actionNaitonality_report_by_period = new QAction(MainWindow);
        actionNaitonality_report_by_period->setObjectName(QString::fromUtf8("actionNaitonality_report_by_period"));
        actionNaitonality_report_by_period->setIcon(icon24);
        actionCancelation_No_show_fees = new QAction(MainWindow);
        actionCancelation_No_show_fees->setObjectName(QString::fromUtf8("actionCancelation_No_show_fees"));
        actionCancelation_No_show_fee = new QAction(MainWindow);
        actionCancelation_No_show_fee->setObjectName(QString::fromUtf8("actionCancelation_No_show_fee"));
        actionSales_by_storages = new QAction(MainWindow);
        actionSales_by_storages->setObjectName(QString::fromUtf8("actionSales_by_storages"));
        actionSales_by_storages->setIcon(icon30);
        actionGuest_by_nationality = new QAction(MainWindow);
        actionGuest_by_nationality->setObjectName(QString::fromUtf8("actionGuest_by_nationality"));
        actionGuest_by_nationality->setIcon(icon24);
        actionModels_of_cars = new QAction(MainWindow);
        actionModels_of_cars->setObjectName(QString::fromUtf8("actionModels_of_cars"));
        QIcon icon34;
        icon34.addFile(QString::fromUtf8(":/images/car.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionModels_of_cars->setIcon(icon34);
        actionCostumers_cars = new QAction(MainWindow);
        actionCostumers_cars->setObjectName(QString::fromUtf8("actionCostumers_cars"));
        actionCostumers_cars->setIcon(icon34);
        actionReport_by_payment = new QAction(MainWindow);
        actionReport_by_payment->setObjectName(QString::fromUtf8("actionReport_by_payment"));
        actionPartners_debts = new QAction(MainWindow);
        actionPartners_debts->setObjectName(QString::fromUtf8("actionPartners_debts"));
        actionCoupons_sales = new QAction(MainWindow);
        actionCoupons_sales->setObjectName(QString::fromUtf8("actionCoupons_sales"));
        actionCoupons_seria = new QAction(MainWindow);
        actionCoupons_seria->setObjectName(QString::fromUtf8("actionCoupons_seria"));
        actionAccounts = new QAction(MainWindow);
        actionAccounts->setObjectName(QString::fromUtf8("actionAccounts"));
        actionAccounts_2 = new QAction(MainWindow);
        actionAccounts_2->setObjectName(QString::fromUtf8("actionAccounts_2"));
        QIcon icon35;
        icon35.addFile(QString::fromUtf8(":/images/refund.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionAccounts_2->setIcon(icon35);
        actionStore_entries = new QAction(MainWindow);
        actionStore_entries->setObjectName(QString::fromUtf8("actionStore_entries"));
        QIcon icon36;
        icon36.addFile(QString::fromUtf8(":/images/storeentry.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionStore_entries->setIcon(icon36);
        actionNew_store_checkpoint = new QAction(MainWindow);
        actionNew_store_checkpoint->setObjectName(QString::fromUtf8("actionNew_store_checkpoint"));
        actionNew_store_checkpoint->setIcon(icon36);
        actionPartner_payments = new QAction(MainWindow);
        actionPartner_payments->setObjectName(QString::fromUtf8("actionPartner_payments"));
        actionCoupons_statistics = new QAction(MainWindow);
        actionCoupons_statistics->setObjectName(QString::fromUtf8("actionCoupons_statistics"));
        actionDebts = new QAction(MainWindow);
        actionDebts->setObjectName(QString::fromUtf8("actionDebts"));
        actionBreakfast_report = new QAction(MainWindow);
        actionBreakfast_report->setObjectName(QString::fromUtf8("actionBreakfast_report"));
        actionDiscount_report = new QAction(MainWindow);
        actionDiscount_report->setObjectName(QString::fromUtf8("actionDiscount_report"));
        actionSales_report_by_cars = new QAction(MainWindow);
        actionSales_report_by_cars->setObjectName(QString::fromUtf8("actionSales_report_by_cars"));
        actionDiscount_total = new QAction(MainWindow);
        actionDiscount_total->setObjectName(QString::fromUtf8("actionDiscount_total"));
        actionCostumers = new QAction(MainWindow);
        actionCostumers->setObjectName(QString::fromUtf8("actionCostumers"));
        actionRefund_voucher = new QAction(MainWindow);
        actionRefund_voucher->setObjectName(QString::fromUtf8("actionRefund_voucher"));
        actionRoom_inventory = new QAction(MainWindow);
        actionRoom_inventory->setObjectName(QString::fromUtf8("actionRoom_inventory"));
        QIcon icon37;
        icon37.addFile(QString::fromUtf8(":/images/configure.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRoom_inventory->setIcon(icon37);
        actionCity_ledger_advance = new QAction(MainWindow);
        actionCity_ledger_advance->setObjectName(QString::fromUtf8("actionCity_ledger_advance"));
        actionTransfer_CL_amount = new QAction(MainWindow);
        actionTransfer_CL_amount->setObjectName(QString::fromUtf8("actionTransfer_CL_amount"));
        actionAvailable_amounts = new QAction(MainWindow);
        actionAvailable_amounts->setObjectName(QString::fromUtf8("actionAvailable_amounts"));
        actionGuest_Tray_Ledger = new QAction(MainWindow);
        actionGuest_Tray_Ledger->setObjectName(QString::fromUtf8("actionGuest_Tray_Ledger"));
        actionGuest_Tray_Ledger->setIcon(icon2);
        actionIn_house_detailed_balance = new QAction(MainWindow);
        actionIn_house_detailed_balance->setObjectName(QString::fromUtf8("actionIn_house_detailed_balance"));
        actionIn_house_detailed_balance->setIcon(icon2);
        actionAvaiable_rooms = new QAction(MainWindow);
        actionAvaiable_rooms->setObjectName(QString::fromUtf8("actionAvaiable_rooms"));
        actionRoom_inventory_2 = new QAction(MainWindow);
        actionRoom_inventory_2->setObjectName(QString::fromUtf8("actionRoom_inventory_2"));
        actionRoom_inventory_2->setIcon(icon37);
        actionRoom_inventory_states = new QAction(MainWindow);
        actionRoom_inventory_states->setObjectName(QString::fromUtf8("actionRoom_inventory_states"));
        QIcon icon38;
        icon38.addFile(QString::fromUtf8(":/images/inventory.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRoom_inventory_states->setIcon(icon38);
        actionList_of_checkin_guests = new QAction(MainWindow);
        actionList_of_checkin_guests->setObjectName(QString::fromUtf8("actionList_of_checkin_guests"));
        actionList_of_checkin_guests->setIcon(icon3);
        actionLenght_of_stay = new QAction(MainWindow);
        actionLenght_of_stay->setObjectName(QString::fromUtf8("actionLenght_of_stay"));
        actionExport_reservations = new QAction(MainWindow);
        actionExport_reservations->setObjectName(QString::fromUtf8("actionExport_reservations"));
        actionExport_reservations->setIcon(icon14);
        actionExecute_failed_sql = new QAction(MainWindow);
        actionExecute_failed_sql->setObjectName(QString::fromUtf8("actionExecute_failed_sql"));
        actionExecute_failed_sql->setIcon(icon14);
        actionT_report = new QAction(MainWindow);
        actionT_report->setObjectName(QString::fromUtf8("actionT_report"));
        QIcon icon39;
        icon39.addFile(QString::fromUtf8(":/images/password.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionT_report->setIcon(icon39);
        actionDisable_second_database = new QAction(MainWindow);
        actionDisable_second_database->setObjectName(QString::fromUtf8("actionDisable_second_database"));
        actionRoom_arrangement = new QAction(MainWindow);
        actionRoom_arrangement->setObjectName(QString::fromUtf8("actionRoom_arrangement"));
        actionRoom_arrangement->setIcon(icon24);
        actionRoom_assignment = new QAction(MainWindow);
        actionRoom_assignment->setObjectName(QString::fromUtf8("actionRoom_assignment"));
        QIcon icon40;
        icon40.addFile(QString::fromUtf8(":/images/storehouse.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRoom_assignment->setIcon(icon40);
        actionWakeup_calls = new QAction(MainWindow);
        actionWakeup_calls->setObjectName(QString::fromUtf8("actionWakeup_calls"));
        QIcon icon41;
        icon41.addFile(QString::fromUtf8(":/images/alarm.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionWakeup_calls->setIcon(icon41);
        actionDaily_transactions = new QAction(MainWindow);
        actionDaily_transactions->setObjectName(QString::fromUtf8("actionDaily_transactions"));
        actionDaily_transactions->setIcon(icon13);
        actionHotel_hierarchy = new QAction(MainWindow);
        actionHotel_hierarchy->setObjectName(QString::fromUtf8("actionHotel_hierarchy"));
        QIcon icon42;
        icon42.addFile(QString::fromUtf8(":/images/hierarchy.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionHotel_hierarchy->setIcon(icon42);
        actionNew_room_chart = new QAction(MainWindow);
        actionNew_room_chart->setObjectName(QString::fromUtf8("actionNew_room_chart"));
        actionCall_rates = new QAction(MainWindow);
        actionCall_rates->setObjectName(QString::fromUtf8("actionCall_rates"));
        actionCall_rates->setIcon(icon5);
        actionTemporary_receipts = new QAction(MainWindow);
        actionTemporary_receipts->setObjectName(QString::fromUtf8("actionTemporary_receipts"));
        actionExpected_arrivals_departures_2 = new QAction(MainWindow);
        actionExpected_arrivals_departures_2->setObjectName(QString::fromUtf8("actionExpected_arrivals_departures_2"));
        actionExpected_arrivals_departures_2->setIcon(icon18);
        actionGuest_Tray_Ledger_By_Date = new QAction(MainWindow);
        actionGuest_Tray_Ledger_By_Date->setObjectName(QString::fromUtf8("actionGuest_Tray_Ledger_By_Date"));
        actionGuest_Tray_Ledger_By_Date->setIcon(icon2);
        actionRecover_invoice = new QAction(MainWindow);
        actionRecover_invoice->setObjectName(QString::fromUtf8("actionRecover_invoice"));
        QIcon icon43;
        icon43.addFile(QString::fromUtf8(":/images/heart-pulses.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRecover_invoice->setIcon(icon43);
        actionPosting_charge_2 = new QAction(MainWindow);
        actionPosting_charge_2->setObjectName(QString::fromUtf8("actionPosting_charge_2"));
        actionTransfer_log = new QAction(MainWindow);
        actionTransfer_log->setObjectName(QString::fromUtf8("actionTransfer_log"));
        actionTransfer_log->setIcon(icon14);
        actionQuick_reservations = new QAction(MainWindow);
        actionQuick_reservations->setObjectName(QString::fromUtf8("actionQuick_reservations"));
        QIcon icon44;
        icon44.addFile(QString::fromUtf8(":/images/bedroom.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionQuick_reservations->setIcon(icon44);
        actionTax_server = new QAction(MainWindow);
        actionTax_server->setObjectName(QString::fromUtf8("actionTax_server"));
        actionQuick_checkout = new QAction(MainWindow);
        actionQuick_checkout->setObjectName(QString::fromUtf8("actionQuick_checkout"));
        QIcon icon45;
        icon45.addFile(QString::fromUtf8(":/images/departure.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionQuick_checkout->setIcon(icon45);
        actionCash_report_items = new QAction(MainWindow);
        actionCash_report_items->setObjectName(QString::fromUtf8("actionCash_report_items"));
        actionPrint_tax_of_checkout_invoices = new QAction(MainWindow);
        actionPrint_tax_of_checkout_invoices->setObjectName(QString::fromUtf8("actionPrint_tax_of_checkout_invoices"));
        actionOptions = new QAction(MainWindow);
        actionOptions->setObjectName(QString::fromUtf8("actionOptions"));
        actionInhouse_guest_future = new QAction(MainWindow);
        actionInhouse_guest_future->setObjectName(QString::fromUtf8("actionInhouse_guest_future"));
        actionInhouse_guest_future->setIcon(icon4);
        actionForecast_occupancy_by_category = new QAction(MainWindow);
        actionForecast_occupancy_by_category->setObjectName(QString::fromUtf8("actionForecast_occupancy_by_category"));
        actionState_of_the_room = new QAction(MainWindow);
        actionState_of_the_room->setObjectName(QString::fromUtf8("actionState_of_the_room"));
        actionState_of_the_room->setIcon(icon7);
        actionExpected_departures_simple = new QAction(MainWindow);
        actionExpected_departures_simple->setObjectName(QString::fromUtf8("actionExpected_departures_simple"));
        actionExpected_departures_simple->setIcon(icon45);
        actionExpected_arivals_simple = new QAction(MainWindow);
        actionExpected_arivals_simple->setObjectName(QString::fromUtf8("actionExpected_arivals_simple"));
        actionExpected_arivals_simple->setIcon(icon18);
        actionArmSoft = new QAction(MainWindow);
        actionArmSoft->setObjectName(QString::fromUtf8("actionArmSoft"));
        QIcon icon46;
        icon46.addFile(QString::fromUtf8(":/images/AS.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionArmSoft->setIcon(icon46);
        actionFiscal_report = new QAction(MainWindow);
        actionFiscal_report->setObjectName(QString::fromUtf8("actionFiscal_report"));
        actionUpload_menu_from_FrontDesk = new QAction(MainWindow);
        actionUpload_menu_from_FrontDesk->setObjectName(QString::fromUtf8("actionUpload_menu_from_FrontDesk"));
        actionUpload_menu_from_FrontDesk->setIcon(icon40);
        actionReceipt_voucher = new QAction(MainWindow);
        actionReceipt_voucher->setObjectName(QString::fromUtf8("actionReceipt_voucher"));
        actionCategory_statistics = new QAction(MainWindow);
        actionCategory_statistics->setObjectName(QString::fromUtf8("actionCategory_statistics"));
        actionCategory_statistics->setIcon(icon24);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        horizontalLayout = new QHBoxLayout(centralWidget);
        horizontalLayout->setSpacing(2);
        horizontalLayout->setContentsMargins(11, 11, 11, 11);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        horizontalLayout->setContentsMargins(2, 2, 2, 2);
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setFocusPolicy(Qt::NoFocus);
        tabWidget->setTabPosition(QTabWidget::North);
        tabWidget->setTabShape(QTabWidget::Rounded);
        tabWidget->setElideMode(Qt::ElideNone);
        tabWidget->setTabsClosable(true);

        horizontalLayout->addWidget(tabWidget);

        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setEnabled(true);
        menuBar->setGeometry(QRect(0, 0, 1375, 21));
        menuWorking = new QMenu(menuBar);
        menuWorking->setObjectName(QString::fromUtf8("menuWorking"));
        menuReservation = new QMenu(menuBar);
        menuReservation->setObjectName(QString::fromUtf8("menuReservation"));
        menuReservation->setTearOffEnabled(false);
        menuAbout = new QMenu(menuBar);
        menuAbout->setObjectName(QString::fromUtf8("menuAbout"));
        menuReports = new QMenu(menuBar);
        menuReports->setObjectName(QString::fromUtf8("menuReports"));
        menuDirectory = new QMenu(menuBar);
        menuDirectory->setObjectName(QString::fromUtf8("menuDirectory"));
        menuApplication = new QMenu(menuBar);
        menuApplication->setObjectName(QString::fromUtf8("menuApplication"));
        menuPreferences = new QMenu(menuApplication);
        menuPreferences->setObjectName(QString::fromUtf8("menuPreferences"));
        menuRestaurant = new QMenu(menuBar);
        menuRestaurant->setObjectName(QString::fromUtf8("menuRestaurant"));
        menuCity_ledger_advance = new QMenu(menuBar);
        menuCity_ledger_advance->setObjectName(QString::fromUtf8("menuCity_ledger_advance"));
        menuReception = new QMenu(menuBar);
        menuReception->setObjectName(QString::fromUtf8("menuReception"));
        menuCachier = new QMenu(menuBar);
        menuCachier->setObjectName(QString::fromUtf8("menuCachier"));
        menuAnalytics = new QMenu(menuBar);
        menuAnalytics->setObjectName(QString::fromUtf8("menuAnalytics"));
        menuOther_Reports = new QMenu(menuBar);
        menuOther_Reports->setObjectName(QString::fromUtf8("menuOther_Reports"));
        menuRestaurant_2 = new QMenu(menuBar);
        menuRestaurant_2->setObjectName(QString::fromUtf8("menuRestaurant_2"));
        menuStorehouse = new QMenu(menuBar);
        menuStorehouse->setObjectName(QString::fromUtf8("menuStorehouse"));
        menuDiscount_system = new QMenu(menuBar);
        menuDiscount_system->setObjectName(QString::fromUtf8("menuDiscount_system"));
        MainWindow->setMenuBar(menuBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuWorking->menuAction());
        menuBar->addAction(menuReservation->menuAction());
        menuBar->addAction(menuReception->menuAction());
        menuBar->addAction(menuCachier->menuAction());
        menuBar->addAction(menuCity_ledger_advance->menuAction());
        menuBar->addAction(menuReports->menuAction());
        menuBar->addAction(menuRestaurant_2->menuAction());
        menuBar->addAction(menuAnalytics->menuAction());
        menuBar->addAction(menuOther_Reports->menuAction());
        menuBar->addAction(menuRestaurant->menuAction());
        menuBar->addAction(menuDirectory->menuAction());
        menuBar->addAction(menuApplication->menuAction());
        menuBar->addAction(menuStorehouse->menuAction());
        menuBar->addAction(menuDiscount_system->menuAction());
        menuBar->addAction(menuAbout->menuAction());
        menuWorking->addAction(actionLogin);
        menuWorking->addAction(actionLogout);
        menuWorking->addAction(actionLock);
        menuWorking->addAction(actionChange_password);
        menuWorking->addSeparator();
        menuWorking->addAction(actionDisable_second_database);
        menuWorking->addAction(actionConfigure_Welcome_Page);
        menuWorking->addAction(actionDatabases);
        menuWorking->addAction(actionPreferences);
        menuWorking->addSeparator();
        menuWorking->addAction(actionExit);
        menuReservation->addAction(actionRoomChart);
        menuReservation->addAction(actionNew_reservation);
        menuReservation->addAction(actionNew_group_reservation);
        menuReservation->addAction(actionReservatios);
        menuReservation->addAction(actionReservations_by_date_created);
        menuReservation->addAction(actionCanceled_reservations);
        menuReservation->addAction(actionReservation_groups);
        menuReservation->addAction(actionCategory_to_sell);
        menuReservation->addAction(actionForecast_Occupancy_Category);
        menuReservation->addAction(actionForecast_occupancy_by_category);
        menuReservation->addAction(actionList_of_source_reservation);
        menuReservation->addAction(actionChanges_of_states_of_room);
        menuReservation->addAction(actionCancelation_No_show_fees);
        menuReservation->addAction(actionAvaiable_rooms);
        menuReservation->addAction(actionLenght_of_stay);
        menuAbout->addAction(actionHelp);
        menuAbout->addAction(actionOptions);
        menuAbout->addAction(actionAbout);
        menuReports->addAction(actionVauchers);
        menuReports->addAction(actionGuest_Tray_Ledger);
        menuReports->addAction(actionGuest_Tray_Ledger_By_Date);
        menuReports->addAction(actionIn_house_detailed_balance);
        menuReports->addAction(actionDaily_movement);
        menuReports->addAction(actionMonthly_Report);
        menuReports->addAction(actionDaily_financial_report);
        menuReports->addAction(actionYearly_financial_report);
        menuReports->addAction(actionInvoices);
        menuReports->addAction(actionCheckout_invoices_free_rooming);
        menuReports->addAction(actionArmSoft);
        menuDirectory->addAction(actionInvoice_items);
        menuDirectory->addAction(actionPartners_group);
        menuDirectory->addAction(actionPartners);
        menuDirectory->addAction(actionCity_Ledger);
        menuDirectory->addAction(actionNationality_file);
        menuDirectory->addAction(actionGuest_titles);
        menuDirectory->addAction(actionGuest_file);
        menuDirectory->addAction(actionCredit_card);
        menuDirectory->addAction(actionSetup_Tax_Printer);
        menuDirectory->addAction(actionCategories);
        menuDirectory->addAction(actionType_of_bed);
        menuDirectory->addAction(actionRoom_view);
        menuDirectory->addAction(actionRoom_list);
        menuDirectory->addAction(actionCall_rates);
        menuDirectory->addAction(actionModels_of_cars);
        menuDirectory->addAction(actionCostumers_cars);
        menuDirectory->addAction(actionAccounts_2);
        menuDirectory->addAction(actionRoom_inventory);
        menuDirectory->addAction(actionRoom_inventory_states);
        menuApplication->addAction(actionUsers_groups);
        menuApplication->addAction(actionUsers);
        menuApplication->addAction(actionTrack_changes);
        menuApplication->addAction(actionGlobal_config);
        menuApplication->addAction(menuPreferences->menuAction());
        menuApplication->addAction(actionReport_buillder);
        menuApplication->addAction(actionExport_invoices);
        menuApplication->addAction(actionExport_active_reservations);
        menuApplication->addAction(actionExport_data);
        menuApplication->addAction(actionExport_reservations);
        menuApplication->addAction(actionUtils);
        menuApplication->addAction(actionWeb);
        menuApplication->addAction(actionExecute_failed_sql);
        menuApplication->addAction(actionTransfer_log);
        menuApplication->addAction(actionRecover_invoice);
        menuApplication->addAction(actionUpload_menu_from_FrontDesk);
        menuPreferences->addAction(actionTax_server);
        menuRestaurant->addAction(actionHakk);
        menuRestaurant->addAction(actionTables);
        menuRestaurant->addAction(actionStorages);
        menuRestaurant->addAction(actionNames_of_menu);
        menuRestaurant->addAction(actionMain_partitions_of_menu);
        menuRestaurant->addAction(actionType_of_dishes);
        menuRestaurant->addAction(actionDishes);
        menuRestaurant->addAction(actionModifiers);
        menuRestaurant->addAction(actionPrinters);
        menuRestaurant->addAction(actionMenu_review);
        menuRestaurant->addAction(actionComplex_dish);
        menuRestaurant->addAction(actionBanquet_comment);
        menuRestaurant->addAction(actionComplimentary_comment);
        menuCity_ledger_advance->addAction(actionCity_Ledger_balance);
        menuCity_ledger_advance->addAction(actionCity_ledger_balance_2);
        menuCity_ledger_advance->addAction(actionCity_Ledger_detailed_balance);
        menuCity_ledger_advance->addAction(actionAvailable_amounts);
        menuReception->addAction(actionQuick_reservations);
        menuReception->addAction(actionQuick_checkout);
        menuReception->addAction(actionIn_house_guest);
        menuReception->addAction(actionInhouse_guest_future);
        menuReception->addAction(actionList_of_checkin_guests);
        menuReception->addAction(actionExpected_arrivals_simple);
        menuReception->addAction(actionExpected_arivals_simple);
        menuReception->addAction(actionExpected_departures_simple);
        menuReception->addAction(actionExpected_arrivals);
        menuReception->addAction(actionExpected_arrivals_departures_2);
        menuReception->addAction(actionDaily_transactions);
        menuReception->addAction(actionRe_checkin);
        menuReception->addAction(actionRoom_assignment);
        menuReception->addAction(actionContacts);
        menuReception->addAction(actionNotes);
        menuReception->addAction(actionRemarks);
        menuReception->addAction(actionHotel_status);
        menuReception->addAction(actionRoom_inventory_2);
        menuReception->addAction(actionWakeup_calls);
        menuReception->addAction(actionHotel_hierarchy);
        menuReception->addAction(actionState_of_the_room);
        menuCachier->addAction(actionNew_advance_entry);
        menuCachier->addAction(actionPosting_charge);
        menuCachier->addAction(actionReceipt_voucher);
        menuCachier->addAction(actionCancelation_No_show_fee);
        menuCachier->addAction(actionDiscount);
        menuCachier->addAction(actionTransfer_amount);
        menuCachier->addAction(actionRefund_voucher);
        menuCachier->addAction(actionCash_report_total);
        menuCachier->addAction(actionCash_repoort_detailed);
        menuCachier->addAction(actionCash_report_items);
        menuCachier->addAction(actionAdvance_report);
        menuCachier->addAction(actionCurrencies);
        menuCachier->addAction(actionTemporary_receipts);
        menuCachier->addAction(actionPrint_tax_of_checkout_invoices);
        menuCachier->addAction(actionFiscal_report);
        menuAnalytics->addAction(actionHistory_of_calls);
        menuAnalytics->addAction(actionCardex_analysis);
        menuAnalytics->addAction(actionReports_set);
        menuAnalytics->addAction(actionStatistics);
        menuAnalytics->addAction(actionMonthly_occupancy_percentages);
        menuAnalytics->addAction(actionNaitonality_report_by_period);
        menuAnalytics->addAction(actionGuest_by_nationality);
        menuAnalytics->addAction(actionRoom_arrangement);
        menuAnalytics->addAction(actionCategory_statistics);
        menuRestaurant_2->addAction(actionRestaurant_online);
        menuRestaurant_2->addAction(actionRestaurant);
        menuRestaurant_2->addAction(actionEvent);
        menuRestaurant_2->addAction(actionBreakfast_report);
        menuRestaurant_2->addAction(actionOpen_breakfast);
        menuRestaurant_2->addAction(actionSales_by_storages);
        menuRestaurant_2->addAction(actionReport_by_payment);
        menuStorehouse->addAction(actionNew_store_document);
        menuStorehouse->addAction(actionPartners_2);
        menuStorehouse->addAction(actionDocuments_list);
        menuStorehouse->addAction(actionStore_movement);
        menuStorehouse->addAction(actionMaterials_in_the_store);
        menuStorehouse->addAction(actionCalculate_output_of_restaurant);
        menuStorehouse->addAction(actionPartners_debts);
        menuStorehouse->addAction(actionPartner_payments);
        menuStorehouse->addAction(actionStore_entries);
        menuStorehouse->addAction(actionNew_store_checkpoint);
        menuStorehouse->addAction(actionT_report);
        menuDiscount_system->addAction(actionCoupons);
        menuDiscount_system->addAction(actionCoupons_seria);
        menuDiscount_system->addAction(actionCoupons_statistics);
        menuDiscount_system->addAction(actionDebts);
        menuDiscount_system->addAction(actionDiscount_report);
        menuDiscount_system->addAction(actionSales_report_by_cars);
        menuDiscount_system->addAction(actionDiscount_total);
        menuDiscount_system->addAction(actionCostumers);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(-1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "SmartHotel", nullptr));
        actionLogin->setText(QCoreApplication::translate("MainWindow", "Login", nullptr));
        actionLogout->setText(QCoreApplication::translate("MainWindow", "Logout", nullptr));
        actionLock->setText(QCoreApplication::translate("MainWindow", "Lock", nullptr));
        actionDatabases->setText(QCoreApplication::translate("MainWindow", "Databases", nullptr));
        actionPreferences->setText(QCoreApplication::translate("MainWindow", "Preferences", nullptr));
        actionExit->setText(QCoreApplication::translate("MainWindow", "Exit", nullptr));
        actionHelp->setText(QCoreApplication::translate("MainWindow", "Help", nullptr));
        actionAbout->setText(QCoreApplication::translate("MainWindow", "About", nullptr));
        actionRoomChart->setText(QCoreApplication::translate("MainWindow", "Room chart", nullptr));
        actionRoom_list->setText(QCoreApplication::translate("MainWindow", "Room list", nullptr));
        actionDaily_movement->setText(QCoreApplication::translate("MainWindow", "Daily movement", nullptr));
        actionGuest_file->setText(QCoreApplication::translate("MainWindow", "Guests", nullptr));
        actionReservatios->setText(QCoreApplication::translate("MainWindow", "Reservations", nullptr));
        actionContacts->setText(QCoreApplication::translate("MainWindow", "Contacts", nullptr));
        actionUsers->setText(QCoreApplication::translate("MainWindow", "Users", nullptr));
        actionUsers_groups->setText(QCoreApplication::translate("MainWindow", "Users groups", nullptr));
        actionRoom_view->setText(QCoreApplication::translate("MainWindow", "Room view", nullptr));
        actionInvoices->setText(QCoreApplication::translate("MainWindow", "Checkout Invoices", nullptr));
        actionNew_reservation->setText(QCoreApplication::translate("MainWindow", "New reservation", nullptr));
        actionPartners->setText(QCoreApplication::translate("MainWindow", "Partners", nullptr));
        actionHakk->setText(QCoreApplication::translate("MainWindow", "Hall", nullptr));
        actionTables->setText(QCoreApplication::translate("MainWindow", "Tables", nullptr));
        actionNames_of_menu->setText(QCoreApplication::translate("MainWindow", "Names of menu", nullptr));
        actionMain_partitions_of_menu->setText(QCoreApplication::translate("MainWindow", "Main partitions of menu", nullptr));
        actionType_of_dishes->setText(QCoreApplication::translate("MainWindow", "Type of dishes", nullptr));
        actionDishes->setText(QCoreApplication::translate("MainWindow", "Dishes", nullptr));
        actionModifiers->setText(QCoreApplication::translate("MainWindow", "Modifiers", nullptr));
        actionStorages->setText(QCoreApplication::translate("MainWindow", "Storages", nullptr));
        actionMenu_review->setText(QCoreApplication::translate("MainWindow", "Menu review", nullptr));
        actionPrinters->setText(QCoreApplication::translate("MainWindow", "Printers", nullptr));
        actionTrack_changes->setText(QCoreApplication::translate("MainWindow", "Track changes", nullptr));
        actionCredit_card->setText(QCoreApplication::translate("MainWindow", "Credit cards", nullptr));
        actionCity_Ledger_balance->setText(QCoreApplication::translate("MainWindow", "Total balance", nullptr));
        actionChange_password->setText(QCoreApplication::translate("MainWindow", "Change password", nullptr));
        actionNew_advance_entry->setText(QCoreApplication::translate("MainWindow", "Advance voucher", nullptr));
        actionGlobal_config->setText(QCoreApplication::translate("MainWindow", "Global config", nullptr));
        actionComplex_dish->setText(QCoreApplication::translate("MainWindow", "Complex dish", nullptr));
        actionCategories->setText(QCoreApplication::translate("MainWindow", "Room categories", nullptr));
        actionType_of_bed->setText(QCoreApplication::translate("MainWindow", "Type of bed", nullptr));
        actionSynchronization->setText(QCoreApplication::translate("MainWindow", "Export POS, Events, Single vauchers", nullptr));
        actionRestaurant->setText(QCoreApplication::translate("MainWindow", "Restaurant", nullptr));
        actionCategory_to_sell->setText(QCoreApplication::translate("MainWindow", "Category to sell", nullptr));
        actionCity_Ledger->setText(QCoreApplication::translate("MainWindow", "City Ledger", nullptr));
        actionCurrencies->setText(QCoreApplication::translate("MainWindow", "Currencies", nullptr));
        actionForecast_Occupancy_Category->setText(QCoreApplication::translate("MainWindow", "Forecast Occupancy / Category", nullptr));
        actionMonthly_Report->setText(QCoreApplication::translate("MainWindow", "Monthly Report", nullptr));
        actionSetup_Tax_Printer->setText(QCoreApplication::translate("MainWindow", "Setup Tax And Hall", nullptr));
        actionInvoice_items->setText(QCoreApplication::translate("MainWindow", "Invoice items", nullptr));
        actionIn_house_guest->setText(QCoreApplication::translate("MainWindow", "In house guest", nullptr));
        actionExpected_arrivals->setText(QCoreApplication::translate("MainWindow", "Expected arrivals / departures", nullptr));
        actionRecheckout->setText(QCoreApplication::translate("MainWindow", "Recheckout", nullptr));
        actionPosting_charge->setText(QCoreApplication::translate("MainWindow", "Posting charge", nullptr));
        actionDiscount->setText(QCoreApplication::translate("MainWindow", "Discount", nullptr));
        actionRe_checkin->setText(QCoreApplication::translate("MainWindow", "Re-checkin", nullptr));
        actionTransfer_amount->setText(QCoreApplication::translate("MainWindow", "Transfer amount", nullptr));
        actionExpected_arrivals_simple->setText(QCoreApplication::translate("MainWindow", "Expected arrivals / pax", nullptr));
        action->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        actionCash_report_total->setText(QCoreApplication::translate("MainWindow", "Cash report / summary", nullptr));
        actionUpdate_program->setText(QCoreApplication::translate("MainWindow", "Update program", nullptr));
        actionReceipt_vaucher->setText(QCoreApplication::translate("MainWindow", "Receipt voucher", nullptr));
        actionCity_Ledger_detailed_balance->setText(QCoreApplication::translate("MainWindow", "Detailed balance", nullptr));
        actionCash_repoort_detailed->setText(QCoreApplication::translate("MainWindow", "Cash report / detailed", nullptr));
        actionVauchers->setText(QCoreApplication::translate("MainWindow", "Vouchers history", nullptr));
        actionNotes->setText(QCoreApplication::translate("MainWindow", "Reminder", nullptr));
        actionCall_history->setText(QCoreApplication::translate("MainWindow", "Call history", nullptr));
        actionEvent->setText(QCoreApplication::translate("MainWindow", "Events", nullptr));
        actionDaily_financial_report->setText(QCoreApplication::translate("MainWindow", "Financial report", nullptr));
        actionBanquet_comment->setText(QCoreApplication::translate("MainWindow", "Banquet comment", nullptr));
        actionCity_ledger_balance_2->setText(QCoreApplication::translate("MainWindow", "Balance by period", nullptr));
        actionHistory_of_calls->setText(QCoreApplication::translate("MainWindow", "History of calls", nullptr));
        actionCardex_analysis->setText(QCoreApplication::translate("MainWindow", "Cardex analysis", nullptr));
        actionExport_invoices->setText(QCoreApplication::translate("MainWindow", "Export invoices", nullptr));
        actionComplimentary_comment->setText(QCoreApplication::translate("MainWindow", "Complimentary comment", nullptr));
        actionExport_active_reservations->setText(QCoreApplication::translate("MainWindow", "Export active reservations", nullptr));
        actionReport_buillder->setText(QCoreApplication::translate("MainWindow", "Report buillder", nullptr));
        actionRemarks->setText(QCoreApplication::translate("MainWindow", "Remarks", nullptr));
        actionHotel_status->setText(QCoreApplication::translate("MainWindow", "Hotel status", nullptr));
        actionList_of_source_reservation->setText(QCoreApplication::translate("MainWindow", "List of source reservation", nullptr));
        actionYearly_financial_report->setText(QCoreApplication::translate("MainWindow", "Yearly financial report", nullptr));
        actionReports_set->setText(QCoreApplication::translate("MainWindow", "Reports set", nullptr));
        actionStatistics->setText(QCoreApplication::translate("MainWindow", "Statistics", nullptr));
        actionUtils->setText(QCoreApplication::translate("MainWindow", "Utils", nullptr));
        actionExport_data->setText(QCoreApplication::translate("MainWindow", "Export other", nullptr));
        actionAdvance_report->setText(QCoreApplication::translate("MainWindow", "Advance report", nullptr));
        actionRestaurant_online->setText(QCoreApplication::translate("MainWindow", "Restaurant online", nullptr));
        actionReservation_groups->setText(QCoreApplication::translate("MainWindow", "Reservation groups", nullptr));
        actionConfigure_Welcome_Page->setText(QCoreApplication::translate("MainWindow", "Configure Welcome Page", nullptr));
        actionPartners_group->setText(QCoreApplication::translate("MainWindow", "Partners group", nullptr));
        actionGuest_titles->setText(QCoreApplication::translate("MainWindow", "Guest titles", nullptr));
        actionNationality_file->setText(QCoreApplication::translate("MainWindow", "Nationality file", nullptr));
        actionCheckout_invoices_free_rooming->setText(QCoreApplication::translate("MainWindow", "Checkout invoices (free rooming)", nullptr));
        actionNew_group_reservation->setText(QCoreApplication::translate("MainWindow", "New group reservation", nullptr));
        actionChanges_of_states_of_room->setText(QCoreApplication::translate("MainWindow", "Changes of states of room", nullptr));
        actionCanceled_reservations->setText(QCoreApplication::translate("MainWindow", "Canceled reservations", nullptr));
        actionWeb->setText(QCoreApplication::translate("MainWindow", "Web", nullptr));
        actionStorehouse->setText(QCoreApplication::translate("MainWindow", "Storehouse", nullptr));
        actionNew_store_document->setText(QCoreApplication::translate("MainWindow", "New store document", nullptr));
        actionMaterials_list->setText(QCoreApplication::translate("MainWindow", "Materials list", nullptr));
        actionReservations_by_date_created->setText(QCoreApplication::translate("MainWindow", "Reservations by date created", nullptr));
        actionPartners_2->setText(QCoreApplication::translate("MainWindow", "Partners", nullptr));
        actionDocuments_list->setText(QCoreApplication::translate("MainWindow", "Documents list", nullptr));
        actionMaterials_in_the_store->setText(QCoreApplication::translate("MainWindow", "Materials in the store", nullptr));
        actionStore_movement->setText(QCoreApplication::translate("MainWindow", "Store movement", nullptr));
        actionCoupons->setText(QCoreApplication::translate("MainWindow", "Coupons", nullptr));
        actionCalculate_output_of_restaurant->setText(QCoreApplication::translate("MainWindow", "Calculate output of restaurant", nullptr));
        actionExport_back->setText(QCoreApplication::translate("MainWindow", "Export back", nullptr));
        actionOpen_breakfast->setText(QCoreApplication::translate("MainWindow", "Open breakfast", nullptr));
        actionMonthly_occupancy_percentages->setText(QCoreApplication::translate("MainWindow", "Monthly occupancy percentages", nullptr));
        actionNaitonality_report_by_period->setText(QCoreApplication::translate("MainWindow", "Nationality by period", nullptr));
        actionCancelation_No_show_fees->setText(QCoreApplication::translate("MainWindow", "Cancelation/No show fees", nullptr));
        actionCancelation_No_show_fee->setText(QCoreApplication::translate("MainWindow", "Cancelation/No show fee", nullptr));
        actionSales_by_storages->setText(QCoreApplication::translate("MainWindow", "Sales by storages", nullptr));
        actionGuest_by_nationality->setText(QCoreApplication::translate("MainWindow", "Guest by nationality", nullptr));
        actionModels_of_cars->setText(QCoreApplication::translate("MainWindow", "Models of cars", nullptr));
        actionCostumers_cars->setText(QCoreApplication::translate("MainWindow", "Costumers (cars)", nullptr));
        actionReport_by_payment->setText(QCoreApplication::translate("MainWindow", "Report by payment", nullptr));
        actionPartners_debts->setText(QCoreApplication::translate("MainWindow", "Partners debts", nullptr));
        actionCoupons_sales->setText(QCoreApplication::translate("MainWindow", "Coupons sales", nullptr));
        actionCoupons_seria->setText(QCoreApplication::translate("MainWindow", "Coupons seria", nullptr));
        actionAccounts->setText(QCoreApplication::translate("MainWindow", "Accounts", nullptr));
        actionAccounts_2->setText(QCoreApplication::translate("MainWindow", "Accounts", nullptr));
        actionStore_entries->setText(QCoreApplication::translate("MainWindow", "Store entries", nullptr));
        actionNew_store_checkpoint->setText(QCoreApplication::translate("MainWindow", "New store checkpoint", nullptr));
        actionPartner_payments->setText(QCoreApplication::translate("MainWindow", "Partner payments", nullptr));
        actionCoupons_statistics->setText(QCoreApplication::translate("MainWindow", "Coupons statistics", nullptr));
        actionDebts->setText(QCoreApplication::translate("MainWindow", "Debts", nullptr));
        actionBreakfast_report->setText(QCoreApplication::translate("MainWindow", "Breakfast", nullptr));
        actionDiscount_report->setText(QCoreApplication::translate("MainWindow", "Discount report", nullptr));
        actionSales_report_by_cars->setText(QCoreApplication::translate("MainWindow", "Sales report by cars", nullptr));
        actionDiscount_total->setText(QCoreApplication::translate("MainWindow", "Discount, total", nullptr));
        actionCostumers->setText(QCoreApplication::translate("MainWindow", "Costumers", nullptr));
        actionRefund_voucher->setText(QCoreApplication::translate("MainWindow", "Refund voucher", nullptr));
        actionRoom_inventory->setText(QCoreApplication::translate("MainWindow", "Room inventory", nullptr));
        actionCity_ledger_advance->setText(QCoreApplication::translate("MainWindow", "City ledger advance", nullptr));
        actionTransfer_CL_amount->setText(QCoreApplication::translate("MainWindow", "Transfer CL amount", nullptr));
        actionAvailable_amounts->setText(QCoreApplication::translate("MainWindow", "Available amounts", nullptr));
        actionGuest_Tray_Ledger->setText(QCoreApplication::translate("MainWindow", "Guest Tray Ledger", nullptr));
        actionIn_house_detailed_balance->setText(QCoreApplication::translate("MainWindow", "In house detailed balance", nullptr));
        actionAvaiable_rooms->setText(QCoreApplication::translate("MainWindow", "Avaiable rooms", nullptr));
        actionRoom_inventory_2->setText(QCoreApplication::translate("MainWindow", "Room inventory", nullptr));
        actionRoom_inventory_states->setText(QCoreApplication::translate("MainWindow", "Room inventory states", nullptr));
        actionList_of_checkin_guests->setText(QCoreApplication::translate("MainWindow", "List of checkin guests", nullptr));
        actionLenght_of_stay->setText(QCoreApplication::translate("MainWindow", "Lenght of stay", nullptr));
        actionExport_reservations->setText(QCoreApplication::translate("MainWindow", "Export reservations", nullptr));
        actionExecute_failed_sql->setText(QCoreApplication::translate("MainWindow", "Execute failed sql queries", nullptr));
        actionT_report->setText(QCoreApplication::translate("MainWindow", "T-report", nullptr));
        actionDisable_second_database->setText(QCoreApplication::translate("MainWindow", "Disable second database", nullptr));
        actionRoom_arrangement->setText(QCoreApplication::translate("MainWindow", "Room arrangement", nullptr));
        actionRoom_assignment->setText(QCoreApplication::translate("MainWindow", "Room assignment", nullptr));
        actionWakeup_calls->setText(QCoreApplication::translate("MainWindow", "Wakeup calls", nullptr));
        actionDaily_transactions->setText(QCoreApplication::translate("MainWindow", "Daily transactions", nullptr));
        actionHotel_hierarchy->setText(QCoreApplication::translate("MainWindow", "Hotel hierarchy", nullptr));
        actionNew_room_chart->setText(QCoreApplication::translate("MainWindow", "New room chart", nullptr));
        actionCall_rates->setText(QCoreApplication::translate("MainWindow", "Call rates", nullptr));
        actionTemporary_receipts->setText(QCoreApplication::translate("MainWindow", "Temporary receipts", nullptr));
        actionExpected_arrivals_departures_2->setText(QCoreApplication::translate("MainWindow", "Expected arrivals / departures 2", nullptr));
        actionGuest_Tray_Ledger_By_Date->setText(QCoreApplication::translate("MainWindow", "Guest Tray Ledger By Date", nullptr));
        actionRecover_invoice->setText(QCoreApplication::translate("MainWindow", "Recover invoice", nullptr));
        actionPosting_charge_2->setText(QCoreApplication::translate("MainWindow", "Posting charge", nullptr));
        actionTransfer_log->setText(QCoreApplication::translate("MainWindow", "Transfer log", nullptr));
        actionQuick_reservations->setText(QCoreApplication::translate("MainWindow", "Quick checkin", nullptr));
        actionTax_server->setText(QCoreApplication::translate("MainWindow", "Tax server", nullptr));
        actionQuick_checkout->setText(QCoreApplication::translate("MainWindow", "Quick checkout", nullptr));
        actionCash_report_items->setText(QCoreApplication::translate("MainWindow", "Cash report / items", nullptr));
        actionPrint_tax_of_checkout_invoices->setText(QCoreApplication::translate("MainWindow", "Print tax of checkout invoices", nullptr));
        actionOptions->setText(QCoreApplication::translate("MainWindow", "Options", nullptr));
        actionInhouse_guest_future->setText(QCoreApplication::translate("MainWindow", "Inhouse guest, future", nullptr));
        actionForecast_occupancy_by_category->setText(QCoreApplication::translate("MainWindow", "Forecast occupancy by category", nullptr));
        actionState_of_the_room->setText(QCoreApplication::translate("MainWindow", "State of the room", nullptr));
        actionExpected_departures_simple->setText(QCoreApplication::translate("MainWindow", "Expected departures / simple", nullptr));
        actionExpected_arivals_simple->setText(QCoreApplication::translate("MainWindow", "Expected arrivals / simple", nullptr));
        actionArmSoft->setText(QCoreApplication::translate("MainWindow", "ArmSoft", nullptr));
        actionFiscal_report->setText(QCoreApplication::translate("MainWindow", "Fiscal report", nullptr));
        actionUpload_menu_from_FrontDesk->setText(QCoreApplication::translate("MainWindow", "Upload menu from FrontDesk", nullptr));
        actionReceipt_voucher->setText(QCoreApplication::translate("MainWindow", "Receipt voucher", nullptr));
        actionCategory_statistics->setText(QCoreApplication::translate("MainWindow", "Category statistics", nullptr));
        menuWorking->setTitle(QCoreApplication::translate("MainWindow", "Working", nullptr));
        menuReservation->setTitle(QCoreApplication::translate("MainWindow", "Reservation", nullptr));
        menuAbout->setTitle(QCoreApplication::translate("MainWindow", "About", nullptr));
        menuReports->setTitle(QCoreApplication::translate("MainWindow", "Bookkeeping", nullptr));
        menuDirectory->setTitle(QCoreApplication::translate("MainWindow", "Directory of Hotel", nullptr));
        menuApplication->setTitle(QCoreApplication::translate("MainWindow", "Application", nullptr));
        menuPreferences->setTitle(QCoreApplication::translate("MainWindow", "Preferences", nullptr));
        menuRestaurant->setTitle(QCoreApplication::translate("MainWindow", "Directory of Restaurant", nullptr));
        menuCity_ledger_advance->setTitle(QCoreApplication::translate("MainWindow", "City ledger ", nullptr));
        menuReception->setTitle(QCoreApplication::translate("MainWindow", "Reception", nullptr));
        menuCachier->setTitle(QCoreApplication::translate("MainWindow", "Cashier", nullptr));
        menuAnalytics->setTitle(QCoreApplication::translate("MainWindow", "Analytics", nullptr));
        menuOther_Reports->setTitle(QCoreApplication::translate("MainWindow", "Other Reports", nullptr));
        menuRestaurant_2->setTitle(QCoreApplication::translate("MainWindow", "Restaurant", nullptr));
        menuStorehouse->setTitle(QCoreApplication::translate("MainWindow", "Storehouse", nullptr));
        menuDiscount_system->setTitle(QCoreApplication::translate("MainWindow", "Discount system", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
