# ---------- Sources (explicit list, no GLOB) ----------
set(SOURCES_RESORT
    about.cpp
    about.h
    about.ui
    appwebsocket.cpp
    appwebsocket.h
    baseextendeddialog.cpp
    baseextendeddialog.h
    basewidget.cpp
    basewidget.h
    consts.h
    databaseconnection.cpp
    databaseconnection.h
    databaseconnection.ui
    databasepasswordchange.cpp
    databasepasswordchange.h
    databasepasswordchange.ui
    databaserow.cpp
    databaserow.h
    databasesconnections.cpp
    databasesconnections.h
    databasesconnections.ui
    dbminvoice.cpp
    dbminvoice.h
    dbmregister.cpp
    dbmregister.h
    dlgadvanceentry.cpp
    dlgadvanceentry.h
    dlgadvanceentry.ui
    dlgcalculateoutputofrestaurant.cpp
    dlgcalculateoutputofrestaurant.h
    dlgcalculateoutputofrestaurant.ui
    dlgcardex.cpp
    dlgcardex.h
    dlgcardex.ui
    dlgcashop.cpp
    dlgcashop.h
    dlgcashop.ui
    dlgchangeclofvaucher.cpp
    dlgchangeclofvaucher.h
    dlgchangeclofvaucher.ui
    dlgchangeexportvaucher.cpp
    dlgchangeexportvaucher.h
    dlgchangeexportvaucher.ui
    dlgchangeremarks.cpp
    dlgchangeremarks.h
    dlgchangeremarks.ui
    dlgchartcolor.cpp
    dlgchartcolor.h
    dlgchartcolor.ui
    dlgchartdaterange.cpp
    dlgchartdaterange.h
    dlgchartdaterange.ui
    dlgcheckadvancebeforecancel.cpp
    dlgcheckadvancebeforecancel.h
    dlgcheckadvancebeforecancel.ui
    dlgcl.cpp
    dlgcl.h
    dlgcl.ui
    dlgclearlog.cpp
    dlgclearlog.h
    dlgclearlog.ui
    dlgclinitialbalance.cpp
    dlgclinitialbalance.h
    dlgclinitialbalance.ui
    dlgconfiggrid.cpp
    dlgconfiggrid.h
    dlgconfiggrid.ui
    dlgconfigtaxserver.cpp
    dlgconfigtaxserver.h
    dlgconfigtaxserver.ui
    dlgcontact.cpp
    dlgcontact.h
    dlgcontact.ui
    dlgcouponsales.cpp
    dlgcouponsales.h
    dlgcouponsales.ui
    dlgcreategroupreservation.cpp
    dlgcreategroupreservation.h
    dlgcreategroupreservation.ui
    dlgdebtpay.cpp
    dlgdebtpay.h
    dlgdebtpay.ui
    dlgdiscount.cpp
    dlgdiscount.h
    dlgdiscount.ui
    dlgdishhistory.cpp
    dlgdishhistory.h
    dlgdishhistory.ui
    dlgeditservtax.cpp
    dlgeditservtax.h
    dlgeditservtax.ui
    dlgemail.cpp
    dlgemail.h
    dlgemail.ui
    dlgendofday.cpp
    dlgendofday.h
    dlgendofday.ui
    dlgexecfailedsqls.cpp
    dlgexecfailedsqls.h
    dlgexecfailedsqls.ui
    dlgexport.cpp
    dlgexport.h
    dlgexport.ui
    dlgexportas.cpp
    dlgexportas.h
    dlgexportas.ui
    dlgexportsinglevaucher.cpp
    dlgexportsinglevaucher.h
    dlgexportsinglevaucher.ui
    dlgfiltervalues.cpp
    dlgfiltervalues.h
    dlgfiltervalues.ui
    dlggposorderinfo.cpp
    dlggposorderinfo.h
    dlggposorderinfo.ui
    dlggroupreservationfuck.cpp
    dlggroupreservationfuck.h
    dlggroupreservationfuck.ui
    dlggroupreserveoption.cpp
    dlggroupreserveoption.h
    dlggroupreserveoption.ui
    dlggrouprevive.cpp
    dlggrouprevive.h
    dlggrouprevive.ui
    dlghdmviewer.cpp
    dlghdmviewer.h
    dlghdmviewer.ui
    dlghelp.cpp
    dlghelp.h
    dlghelp.ui
    dlghouseitem.cpp
    dlghouseitem.h
    dlghouseitem.ui
    dlghouseitemonoffwidget.cpp
    dlghouseitemonoffwidget.h
    dlghouseitemonoffwidget.ui
    dlginvoicecancelation.cpp
    dlginvoicecancelation.h
    dlginvoicecancelation.ui
    dlginvoicepaymentoptions.cpp
    dlginvoicepaymentoptions.h
    dlginvoicepaymentoptions.ui
    dlginvoiceprintoption.cpp
    dlginvoiceprintoption.h
    dlginvoiceprintoption.ui
    dlginvoicetocl.cpp
    dlginvoicetocl.h
    dlginvoicetocl.ui
    dlgmovetocl.cpp
    dlgmovetocl.h
    dlgmovetocl.ui
    dlgnewvaucheroption.cpp
    dlgnewvaucheroption.h
    dlgnewvaucheroption.ui
    dlgnoshow.cpp
    dlgnoshow.h
    dlgnoshow.ui
    dlgnotes.cpp
    dlgnotes.h
    dlgnotes.ui
    dlgofferinvoiceextra.cpp
    dlgofferinvoiceextra.h
    dlgofferinvoiceextra.ui
    dlgopengrouporsingle.cpp
    dlgopengrouporsingle.h
    dlgopengrouporsingle.ui
    dlgoptions.cpp
    dlgoptions.h
    dlgoptions.ui
    dlgpartnerpayment.cpp
    dlgpartnerpayment.h
    dlgpartnerpayment.ui
    dlgpaymentmode.cpp
    dlgpaymentmode.h
    dlgpaymentmode.ui
    dlgpaymentsdetails.cpp
    dlgpaymentsdetails.h
    dlgpaymentsdetails.ui
    dlgperemovereason.cpp
    dlgperemovereason.h
    dlgperemovereason.ui
    dlgposremoveoption.ui
    dlgpostbreakfast.cpp
    dlgpostbreakfast.h
    dlgpostbreakfast.ui
    dlgpostcharge.cpp
    dlgpostcharge.h
    dlgpostcharge.ui
    dlgpretax.cpp
    dlgpretax.h
    dlgpretax.ui
    dlgprintrandomtax.cpp
    dlgprintrandomtax.h
    dlgprintrandomtax.ui
    dlgprinttaxsideoption.cpp
    dlgprinttaxsideoption.h
    dlgprinttaxsideoption.ui
    dlgprinttaxsm.cpp
    dlgprinttaxsm.h
    dlgprinttaxsm.ui
    dlgprintvoucherasinvoice.cpp
    dlgprintvoucherasinvoice.h
    dlgprintvoucherasinvoice.ui
    dlgquickadvance.cpp
    dlgquickadvance.h
    dlgquickadvance.ui
    dlgquickadvanceaction.cpp
    dlgquickadvanceaction.h
    dlgquickadvanceaction.ui
    dlgquickadvanceapply.cpp
    dlgquickadvanceapply.h
    dlgquickadvanceapply.ui
    dlgquickroomassignment.cpp
    dlgquickroomassignment.h
    dlgquickroomassignment.ui
    dlgraiseuser.cpp
    dlgraiseuser.h
    dlgraiseuser.ui
    dlgreceiptvaucher.cpp
    dlgreceiptvaucher.h
    dlgreceiptvaucher.ui
    dlgrefundvaucher.cpp
    dlgrefundvaucher.h
    dlgrefundvaucher.ui
    dlgremotinvoices.cpp
    dlgremotinvoices.h
    dlgremotinvoices.ui
    dlgreportbuildergroups.cpp
    dlgreportbuildergroups.h
    dlgreportbuildergroups.ui
    dlgreservationdateprices.cpp
    dlgreservationdateprices.h
    dlgreservationdateprices.ui
    dlgreservationguests.cpp
    dlgreservationguests.h
    dlgreservationguests.ui
    dlgreservationremarks.cpp
    dlgreservationremarks.h
    dlgreservationremarks.ui
    dlgreserveconfirmstatus.cpp
    dlgreserveconfirmstatus.h
    dlgreserveconfirmstatus.ui
    dlgreserveshortinfo.cpp
    dlgreserveshortinfo.h
    dlgreserveshortinfo.ui
    dlgroom.cpp
    dlgroom.h
    dlgroom.ui
    dlgroomview.cpp
    dlgroomview.h
    dlgroomview.ui
    dlgseachfromdatabase.cpp
    dlgseachfromdatabase.h
    dlgseachfromdatabase.ui
    dlgsearchinvoice.cpp
    dlgsearchinvoice.h
    dlgsearchinvoice.ui
    dlgselectfiscalmachin.cpp
    dlgselectfiscalmachin.h
    dlgselectfiscalmachin.ui
    dlgsimpleselectroom.cpp
    dlgsimpleselectroom.h
    dlgsimpleselectroom.ui
    dlgsingleprinttax.cpp
    dlgsingleprinttax.h
    dlgsingleprinttax.ui
    dlgtaxback.cpp
    dlgtaxback.h
    dlgtaxback.ui
    dlgtaxback2.cpp
    dlgtaxback2.h
    dlgtaxback2.ui
    dlgtaxprintsetup.cpp
    dlgtaxprintsetup.h
    dlgtaxprintsetup.ui
    dlgtaxreference.cpp
    dlgtaxreference.h
    dlgtaxreference.ui
    dlgtracking.cpp
    dlgtracking.h
    dlgtracking.ui
    dlgtransfer.cpp
    dlgtransfer.h
    dlgtransfer.ui
    dlgtransferanyamount.cpp
    dlgtransferanyamount.h
    dlgtransferanyamount.ui
    dlgusergroup.cpp
    dlgusergroup.h
    dlgusergroup.ui
    dlguserpasswords.cpp
    dlguserpasswords.h
    dlguserpasswords.ui
    dlguserrights.cpp
    dlguserrights.h
    dlguserrights.ui
    dlgutils.cpp
    dlgutils.h
    dlgutils.ui
    dlgviewinvoicecorrections.cpp
    dlgviewinvoicecorrections.h
    dlgviewinvoicecorrections.ui
    dlgwakepcalls.cpp
    dlgwakepcalls.h
    dlgwakepcalls.ui
    dlgwelcomebuttonconfig.cpp
    dlgwelcomebuttonconfig.h
    dlgwelcomebuttonconfig.ui
    dwmaindeskhint.cpp
    dwmaindeskhint.h
    dwmaindeskhint.ui
    fnatbyperiod.cpp
    fnatbyperiod.h
    fnatbyperiod.ui
    fnousedadvance.cpp
    fnousedadvance.h
    fnousedadvance.ui
    fonlinebreakfast.cpp
    fonlinebreakfast.h
    fonlinebreakfast.ui
    fonlinerest.cpp
    fonlinerest.h
    fonlinerest.ui
    fpartnersdebt.cpp
    fpartnersdebt.h
    fpartnersdebt.ui
    goexpextedarrivals.cpp
    goexpextedarrivals.h
    goexpextedarrivals.ui
    login.cpp
    login.h
    login.ui
    loginsettings.cpp
    loginsettings.h
    loginsettings.ui
    main.cpp
    mainwindow.cpp
    mainwindow.h
    mainwindow.ui
    message.cpp
    message.h
    message.ui
    printtaxno.cpp
    printtaxno.h
    rc.h
    reroomcategoryraterow.cpp
    reroomcategoryraterow.h
    reroomcategoryraterow.ui
    res.qrc
    res.rc
    roweditordialog.cpp
    roweditordialog.h
    smtp.cpp
    smtp.h
    tablemodel.cpp
    tablemodel.h
    taxhelper.cpp
    taxhelper.h
    timerblya.cpp
    timerblya.h
    travelline.cpp
    travelline.h
    travelline.ui
    waccinvoice.cpp
    waccinvoice.h
    waccinvoice.ui
    wactivegroup.cpp
    wactivegroup.h
    wactivegroup.ui
    wcardex.cpp
    wcardex.h
    wcardex.ui
    wcheckboxgroup.cpp
    wcheckboxgroup.h
    wcityledger.cpp
    wcityledger.h
    wcityledger.ui
    wcontacts.cpp
    wcontacts.h
    wglobaldbconfig.cpp
    wglobaldbconfig.h
    wglobaldbconfig.ui
    wgroupreserverect.cpp
    wgroupreserverect.h
    wgroupreserverect.ui
    wguest.cpp
    wguest.h
    wguest.ui
    wguestinvoice.cpp
    wguestinvoice.h
    wguestinvoice.ui
    wguests.cpp
    wguests.h
    whomepage.cpp
    whomepage.h
    whomepage.ui
    winvoice.cpp
    winvoice.h
    winvoice.ui
    wmaindesk.cpp
    wmaindesk.h
    wmaindesk.ui
    wmaindeskfilterlist.cpp
    wmaindeskfilterlist.h
    wmaindeskfilterlist.ui
    wnotes.cpp
    wnotes.h
    wpaymentdetails.cpp
    wpaymentdetails.h
    wpaymentdetails.ui
    wquickcheckout.cpp
    wquickcheckout.h
    wquickcheckout.ui
    wquickcheckoutbalance.cpp
    wquickcheckoutbalance.h
    wquickcheckoutbalance.ui
    wquickcheckoutprocess.cpp
    wquickcheckoutprocess.h
    wquickcheckoutprocess.ui
    wquickreservations.cpp
    wquickreservations.h
    wquickreservations.ui
    wquickreservationscheckin.cpp
    wquickreservationscheckin.h
    wquickreservationscheckin.ui
    wquickreservationsguests.cpp
    wquickreservationsguests.h
    wquickreservationsguests.ui
    wquickreservationspax.cpp
    wquickreservationspax.h
    wquickreservationspax.ui
    wquickroomassignment.cpp
    wquickroomassignment.h
    wquickroomassignment.ui
    wreportgrid.cpp
    wreportgrid.h
    wreportgrid.ui
    wreportroom.cpp
    wreportroom.h
    wreservation.cpp
    wreservation.h
    wreservation.ui
    wreservationroomtab.cpp
    wreservationroomtab.h
    wreservationroomtab.ui
    wreservations.cpp
    wreservations.h
    wroomchart.cpp
    wroomchart.h
    wroomchart.ui
    wroomchartclasses.cpp
    wroomchartclasses.h
    wroomchartdock.cpp
    wroomchartdock.h
    wroomchartdock.ui
    wroomcharttemprectdlg.cpp
    wroomcharttemprectdlg.h
    wroomcharttemprectdlg.ui
    wroomcharttime.cpp
    wroomcharttime.h
    wroomview.cpp
    wroomview.h
    wtaxattack.cpp
    wtaxattack.h
    wtaxattack.ui
    wusers.cpp
    wusers.h
    wusersgroups.cpp
    wusersgroups.h
    wwelcome.cpp
    wwelcome.h
    wwelcome.ui
)

set(SOURCES_BASE
    ../Base/appconfig.cpp
    ../Base/appconfig.h
    ../Base/base.cpp
    ../Base/base.h
    ../Base/basedialog.cpp
    ../Base/basedialog.h
    ../Base/baseuid.cpp
    ../Base/baseuid.h
    ../Base/defines.cpp
    ../Base/defines.h
    ../Base/appimages.cpp
    ../Base/appimages.h
    ../Base/defrest.cpp
    ../Base/defrest.h
    ../Base/defstore.h
    ../Base/dlgexitbyversion.cpp
    ../Base/dlgexitbyversion.h
    ../Base/dlgexitbyversion.ui
    ../Base/dlgselector.cpp
    ../Base/dlgselector.h
    ../Base/dlgselector.ui
    ../Base/doubledatabase.cpp
    ../Base/doubledatabase.h
    ../Base/doubleutils.cpp
    ../Base/doubleutils.h
    ../Base/logging.cpp
    ../Base/logging.h
    ../Base/monthnames.cpp
    ../Base/monthnames.h
    ../Base/paymentmode.cpp
    ../Base/paymentmode.h
    ../Base/preferences.cpp
    ../Base/preferences.h
    ../Base/stringutils.cpp
    ../Base/stringutils.h
    ../Base/travellineconfig.cpp
    ../Base/travellineconfig.h
    ../Base/user.cpp
    ../Base/user.h
    ../Base/utils.cpp
    ../Base/utils.h
    ../Base/vauchers.cpp
    ../Base/vauchers.h
)

set(SOURCES_CACHE
    ../Cache/cacheactivegroup.cpp
    ../Cache/cacheactivegroup.h
    ../Cache/cacheactiveroom.cpp
    ../Cache/cacheactiveroom.h
    ../Cache/cachebasestruct.cpp
    ../Cache/cachebasestruct.h
    ../Cache/cachebed.cpp
    ../Cache/cachebed.h
    ../Cache/cachecar.cpp
    ../Cache/cachecar.h
    ../Cache/cachecardex.cpp
    ../Cache/cachecardex.h
    ../Cache/cachecardexgroup.cpp
    ../Cache/cachecardexgroup.h
    ../Cache/cachecashdesk.cpp
    ../Cache/cachecashdesk.h
    ../Cache/cachecashdoc.cpp
    ../Cache/cachecashdoc.h
    ../Cache/cachecheckoutinvoice.cpp
    ../Cache/cachecheckoutinvoice.h
    ../Cache/cacherefundinvoice.cpp
    ../Cache/cacherefundinvoice.h
    ../Cache/cachecityledger.cpp
    ../Cache/cachecityledger.h
    ../Cache/cachecladvance.cpp
    ../Cache/cachecladvance.h
    ../Cache/cachecouponseria.cpp
    ../Cache/cachecouponseria.h
    ../Cache/cachecoupontype.cpp
    ../Cache/cachecoupontype.h
    ../Cache/cachecreditcard.cpp
    ../Cache/cachecreditcard.h
    ../Cache/cachecurrencies.cpp
    ../Cache/cachecurrencies.h
    ../Cache/cachedebtcostumer.cpp
    ../Cache/cachedebtcostumer.h
    ../Cache/cachedish.cpp
    ../Cache/cachedish.h
    ../Cache/cachedishstate.cpp
    ../Cache/cachedishstate.h
    ../Cache/cachedocpayment.cpp
    ../Cache/cachedocpayment.h
    ../Cache/cachefiscalmachine.cpp
    ../Cache/cachefiscalmachine.h
    ../Cache/cachegroupreservations.cpp
    ../Cache/cachegroupreservations.h
    ../Cache/cacheguest.cpp
    ../Cache/cacheguest.h
    ../Cache/cacheguesttitle.cpp
    ../Cache/cacheguesttitle.h
    ../Cache/cacheinstance.cpp
    ../Cache/cacheinstance.h
    ../Cache/cacheinvoiceitem.cpp
    ../Cache/cacheinvoiceitem.h
    ../Cache/cacheinvoiceitemgroup.cpp
    ../Cache/cacheinvoiceitemgroup.h
    ../Cache/cachemenudishes.cpp
    ../Cache/cachemenudishes.h
    ../Cache/cachenation.cpp
    ../Cache/cachenation.h
    ../Cache/cacheone.cpp
    ../Cache/cacheone.h
    ../Cache/cacheorderstate.cpp
    ../Cache/cacheorderstate.h
    ../Cache/cachepaymentmode.cpp
    ../Cache/cachepaymentmode.h
    ../Cache/cacheredreservation.cpp
    ../Cache/cacheredreservation.h
    ../Cache/cachereminderstate.cpp
    ../Cache/cachereminderstate.h
    ../Cache/cachereservation.cpp
    ../Cache/cachereservation.h
    ../Cache/cachereservationcardex.cpp
    ../Cache/cachereservationcardex.h
    ../Cache/cachereservegroup.cpp
    ../Cache/cachereservegroup.h
    ../Cache/cachereservestate.cpp
    ../Cache/cachereservestate.h
    ../Cache/cachereservestatus.cpp
    ../Cache/cachereservestatus.h
    ../Cache/cacherestdebtholder.cpp
    ../Cache/cacherestdebtholder.h
    ../Cache/cacherestdishmod.cpp
    ../Cache/cacherestdishmod.h
    ../Cache/cacherestdishpart.cpp
    ../Cache/cacherestdishpart.h
    ../Cache/cacherestdishtype.cpp
    ../Cache/cacherestdishtype.h
    ../Cache/cacherestfullmenu.cpp
    ../Cache/cacherestfullmenu.h
    ../Cache/cacheresthall.cpp
    ../Cache/cacheresthall.h
    ../Cache/cacherestmenu.cpp
    ../Cache/cacherestmenu.h
    ../Cache/cacherestprinters.cpp
    ../Cache/cacherestprinters.h
    ../Cache/cachereststore.cpp
    ../Cache/cachereststore.h
    ../Cache/cacheresttable.cpp
    ../Cache/cacheresttable.h
    ../Cache/cacherights.cpp
    ../Cache/cacherights.h
    ../Cache/cacheroom.cpp
    ../Cache/cacheroom.h
    ../Cache/cacheroomarrangment.cpp
    ../Cache/cacheroomarrangment.h
    ../Cache/cacheroomcategory.cpp
    ../Cache/cacheroomcategory.h
    ../Cache/cacheroomextra.cpp
    ../Cache/cacheroomextra.h
    ../Cache/cacheroominventory.cpp
    ../Cache/cacheroominventory.h
    ../Cache/cacheroominventorystate.cpp
    ../Cache/cacheroominventorystate.h
    ../Cache/cacheroomstate.cpp
    ../Cache/cacheroomstate.h
    ../Cache/cacheroomview.cpp
    ../Cache/cacheroomview.h
    ../Cache/cachesex.cpp
    ../Cache/cachesex.h
    ../Cache/cachestoredoc.cpp
    ../Cache/cachestoredoc.h
    ../Cache/cachestoredocstate.cpp
    ../Cache/cachestoredocstate.h
    ../Cache/cachestorepartners.cpp
    ../Cache/cachestorepartners.h
    ../Cache/cachetaxmap.cpp
    ../Cache/cachetaxmap.h
    ../Cache/cachetrackingtables.cpp
    ../Cache/cachetrackingtables.h
    ../Cache/cachetransferfromcl.cpp
    ../Cache/cachetransferfromcl.h
    ../Cache/cachetraveline.h
    ../Cache/cacheusers.cpp
    ../Cache/cacheusers.h
    ../Cache/cacheusersgroups.cpp
    ../Cache/cacheusersgroups.h
    ../Cache/cacheusersstate.cpp
    ../Cache/cacheusersstate.h
    ../Cache/cachevatmode.cpp
    ../Cache/cachevatmode.h
    ../Cache/cachevaucher.cpp
    ../Cache/cachevaucher.h
    ../Cache/cacheyear.cpp
    ../Cache/cacheyear.h
)

set(SOURCES_CACHE2
    ../Cache2/cache2.cpp
    ../Cache2/cache2.h
)

set(SOURCES_CONTROLS
    ../Controls/ecolorlineedit.cpp
    ../Controls/ecolorlineedit.h
    ../Controls/ecomboboxcompleter.cpp
    ../Controls/ecomboboxcompleter.h
    ../Controls/ecombomonth.cpp
    ../Controls/ecombomonth.h
    ../Controls/edateedit.cpp
    ../Controls/edateedit.h
    ../Controls/edoubleedit.cpp
    ../Controls/edoubleedit.h
    ../Controls/efilterlineedit.cpp
    ../Controls/efilterlineedit.h
    ../Controls/efilterlineedit.ui
    ../Controls/epushbutton.cpp
    ../Controls/epushbutton.h
    ../Controls/eqcheckbox.cpp
    ../Controls/eqcheckbox.h
    ../Controls/eqcombobox.cpp
    ../Controls/eqcombobox.h
    ../Controls/eqdateedit.cpp
    ../Controls/eqdateedit.h
    ../Controls/eqdoubleedit.cpp
    ../Controls/eqdoubleedit.h
    ../Controls/eqlineedit.cpp
    ../Controls/eqlineedit.h
    ../Controls/eqspinbox.cpp
    ../Controls/eqspinbox.h
    ../Controls/eqtablewidget.cpp
    ../Controls/eqtablewidget.h
    ../Controls/eqtextedit.cpp
    ../Controls/eqtextedit.h
    ../Controls/eqtimeedit.cpp
    ../Controls/eqtimeedit.h
    ../Controls/eradiobutton.cpp
    ../Controls/eradiobutton.h
    ../Controls/etoolbarbutton.cpp
    ../Controls/etoolbarbutton.h
    ../Controls/eyearcombo.cpp
    ../Controls/eyearcombo.h
    ../Controls/radiogroupwidget.cpp
    ../Controls/radiogroupwidget.h
    ../Controls/tableview.cpp
    ../Controls/tableview.h
    ../Controls/trackcontrol.cpp
    ../Controls/trackcontrol.h
)

set(SOURCES_ROWEDITOR
    ../RowEditor/rebanquetcomment.cpp
    ../RowEditor/rebanquetcomment.h
    ../RowEditor/rebanquetcomment.ui
    ../RowEditor/recallrate.cpp
    ../RowEditor/recallrate.h
    ../RowEditor/recallrate.ui
    ../RowEditor/recarclient.cpp
    ../RowEditor/recarclient.h
    ../RowEditor/recarclient.ui
    ../RowEditor/recardexgroup.cpp
    ../RowEditor/recardexgroup.h
    ../RowEditor/recardexgroup.ui
    ../RowEditor/recityledger.cpp
    ../RowEditor/recityledger.h
    ../RowEditor/recityledger.ui
    ../RowEditor/recomplimentarycomment.cpp
    ../RowEditor/recomplimentarycomment.h
    ../RowEditor/recomplimentarycomment.ui
    ../RowEditor/recreditcard.cpp
    ../RowEditor/recreditcard.h
    ../RowEditor/recreditcard.ui
    ../RowEditor/recurrency.cpp
    ../RowEditor/recurrency.h
    ../RowEditor/recurrency.ui
    ../RowEditor/recustomaction.cpp
    ../RowEditor/recustomaction.h
    ../RowEditor/refiscalmachine.cpp
    ../RowEditor/refiscalmachine.h
    ../RowEditor/refiscalmachine.ui
    ../RowEditor/reimage.cpp
    ../RowEditor/reimage.h
    ../RowEditor/reimage.ui
    ../RowEditor/reguesttitle.cpp
    ../RowEditor/reguesttitle.h
    ../RowEditor/reguesttitle.ui
    ../RowEditor/rehouseitem.cpp
    ../RowEditor/rehouseitem.h
    ../RowEditor/rehouseitem.ui
    ../RowEditor/reinvoiceitem.cpp
    ../RowEditor/reinvoiceitem.h
    ../RowEditor/reinvoiceitem.ui
    ../RowEditor/remodelofcars.cpp
    ../RowEditor/remodelofcars.h
    ../RowEditor/remodelofcars.ui
    ../RowEditor/renationalityfile.cpp
    ../RowEditor/renationalityfile.h
    ../RowEditor/renationalityfile.ui
    ../RowEditor/rerestdish.cpp
    ../RowEditor/rerestdish.h
    ../RowEditor/rerestdish.ui
    ../RowEditor/rerestdishcomplex.cpp
    ../RowEditor/rerestdishcomplex.h
    ../RowEditor/rerestdishcomplex.ui
    ../RowEditor/rerestdishmod.cpp
    ../RowEditor/rerestdishmod.h
    ../RowEditor/rerestdishmod.ui
    ../RowEditor/rerestdishtype.cpp
    ../RowEditor/rerestdishtype.h
    ../RowEditor/rerestdishtype.ui
    ../RowEditor/reresthall.cpp
    ../RowEditor/reresthall.h
    ../RowEditor/reresthall.ui
    ../RowEditor/rerestmenunames.cpp
    ../RowEditor/rerestmenunames.h
    ../RowEditor/rerestmenunames.ui
    ../RowEditor/rerestmenupart.cpp
    ../RowEditor/rerestmenupart.h
    ../RowEditor/rerestmenupart.ui
    ../RowEditor/rerestprinter.cpp
    ../RowEditor/rerestprinter.h
    ../RowEditor/rerestprinter.ui
    ../RowEditor/rereststore.cpp
    ../RowEditor/rereststore.h
    ../RowEditor/rereststore.ui
    ../RowEditor/reresttable.cpp
    ../RowEditor/reresttable.h
    ../RowEditor/reresttable.ui
    ../RowEditor/reroombed.cpp
    ../RowEditor/reroombed.h
    ../RowEditor/reroombed.ui
    ../RowEditor/reroomcategory.cpp
    ../RowEditor/reroomcategory.h
    ../RowEditor/reroomcategory.ui
    ../RowEditor/reroomcategoryrate.cpp
    ../RowEditor/reroomcategoryrate.h
    ../RowEditor/reroomcategoryrate.ui
    ../RowEditor/reroominventory.cpp
    ../RowEditor/reroominventory.h
    ../RowEditor/reroominventory.ui
    ../RowEditor/reroominventorystate.cpp
    ../RowEditor/reroominventorystate.h
    ../RowEditor/reroominventorystate.ui
    ../RowEditor/restorepartner.cpp
    ../RowEditor/restorepartner.h
    ../RowEditor/restorepartner.ui
    ../RowEditor/reusers.cpp
    ../RowEditor/reusers.h
    ../RowEditor/reusers.ui
)

set(SOURCES_ROOMCHART
    ../RoomChart/chardefaults.cpp
    ../RoomChart/chardefaults.h
    ../RoomChart/dayitemdelegate.cpp
    ../RoomChart/dayitemdelegate.h
    ../RoomChart/dlgooroomprop.cpp
    ../RoomChart/dlgooroomprop.h
    ../RoomChart/dlgooroomprop.ui
    ../RoomChart/dlgreservequickinfo.cpp
    ../RoomChart/dlgreservequickinfo.h
    ../RoomChart/dlgreservequickinfo.ui
    ../RoomChart/monthitemdelegate.cpp
    ../RoomChart/monthitemdelegate.h
    ../RoomChart/reservationinfo.cpp
    ../RoomChart/reservationinfo.h
    ../RoomChart/reserverect.cpp
    ../RoomChart/reserverect.h
    ../RoomChart/reservewidget.cpp
    ../RoomChart/reservewidget.h
    ../RoomChart/reservewidget.ui
    ../RoomChart/reservewidgetaction.cpp
    ../RoomChart/reservewidgetaction.h
    ../RoomChart/reservewidgetaction.ui
    ../RoomChart/roomitemdelegate.cpp
    ../RoomChart/roomitemdelegate.h
    ../RoomChart/roomscene.cpp
    ../RoomChart/roomscene.h
    ../RoomChart/roomstate.cpp
    ../RoomChart/roomstate.h
    ../RoomChart/roomstate.ui
)

set(SOURCES_FILTER
    ../Filter/faccmonthlyreport.cpp
    ../Filter/faccmonthlyreport.h
    ../Filter/faccmonthlyreport.ui
    ../Filter/fallguestindaterange.cpp
    ../Filter/fallguestindaterange.h
    ../Filter/fallguestindaterange.ui
    ../Filter/favailablerooms.cpp
    ../Filter/favailablerooms.h
    ../Filter/favailablerooms.ui
    ../Filter/fbreakfast.cpp
    ../Filter/fbreakfast.h
    ../Filter/fbreakfast.ui
    ../Filter/fcallhistory.cpp
    ../Filter/fcallhistory.h
    ../Filter/fcallhistory.ui
    ../Filter/fcallrates.cpp
    ../Filter/fcallrates.h
    ../Filter/fcallrates.ui
    ../Filter/fcanceledreservations.cpp
    ../Filter/fcanceledreservations.h
    ../Filter/fcanceledreservations.ui
    ../Filter/fcardexsales.cpp
    ../Filter/fcardexsales.h
    ../Filter/fcardexsales.ui
    ../Filter/fcashreport.cpp
    ../Filter/fcashreport.h
    ../Filter/fcashreport.ui
    ../Filter/fcashreportbyitem.cpp
    ../Filter/fcashreportbyitem.h
    ../Filter/fcashreportbyitem.ui
    ../Filter/fcashreportsummary.cpp
    ../Filter/fcashreportsummary.h
    ../Filter/fcashreportsummary.ui
    ../Filter/fcategorytosell.cpp
    ../Filter/fcategorytosell.h
    ../Filter/fcategorytosell.ui
    ../Filter/fcityledgerbalance.cpp
    ../Filter/fcityledgerbalance.h
    ../Filter/fcityledgerbalance.ui
    ../Filter/fcityledgerbalanceextended.cpp
    ../Filter/fcityledgerbalanceextended.h
    ../Filter/fcityledgerbalanceextended.ui
    ../Filter/fcityledgerdetailedbalance.cpp
    ../Filter/fcityledgerdetailedbalance.h
    ../Filter/fcityledgerdetailedbalance.ui
    ../Filter/fcitytrayledger.cpp
    ../Filter/fcitytrayledger.h
    ../Filter/fcitytrayledger.ui
    ../Filter/fcitytrayledger2.cpp
    ../Filter/fcitytrayledger2.h
    ../Filter/fcitytrayledger2.ui
    ../Filter/fcladvance.cpp
    ../Filter/fcladvance.h
    ../Filter/fcladvance.ui
    ../Filter/fcommonfilterbydate.cpp
    ../Filter/fcommonfilterbydate.h
    ../Filter/fcommonfilterbydate.ui
    ../Filter/fcouponstatistics.cpp
    ../Filter/fcouponstatistics.h
    ../Filter/fcouponstatistics.ui
    ../Filter/fdailymovement.cpp
    ../Filter/fdailymovement.h
    ../Filter/fdailymovement.ui
    ../Filter/fdailymovementcommon.cpp
    ../Filter/fdailymovementcommon.h
    ../Filter/fdailymovementcommon.ui
    ../Filter/fdailytransaction.cpp
    ../Filter/fdailytransaction.h
    ../Filter/fdailytransaction.ui
    ../Filter/fdiscounttotal.ui
    ../Filter/fdishes.cpp
    ../Filter/fdishes.h
    ../Filter/fdishes.ui
    ../Filter/fevents.cpp
    ../Filter/fevents.h
    ../Filter/fevents.ui
    ../Filter/fexpectedarrivals.cpp
    ../Filter/fexpectedarrivals.h
    ../Filter/fexpectedarrivals.ui
    ../Filter/fexpectedarrivals2.cpp
    ../Filter/fexpectedarrivals2.h
    ../Filter/fexpectedarrivals2.ui
    ../Filter/fexpectedarrivalsimple.cpp
    ../Filter/fexpectedarrivalsimple.h
    ../Filter/fexpectedarrivalsimple.ui
    ../Filter/fexpecteddeparturesimple.cpp
    ../Filter/fexpecteddeparturesimple.h
    ../Filter/fexpecteddeparturesimple.ui
    ../Filter/fexpectedsimple.cpp
    ../Filter/fexpectedsimple.h
    ../Filter/fexpectedsimple.ui
    ../Filter/fexportreservation.cpp
    ../Filter/fexportreservation.h
    ../Filter/fexportreservation.ui
    ../Filter/fforecastoccupancycategory.cpp
    ../Filter/fforecastoccupancycategory.h
    ../Filter/fforecastoccupancycategory.ui
    ../Filter/fhotelhierarchy.cpp
    ../Filter/fhotelhierarchy.h
    ../Filter/fhotelhierarchy.ui
    ../Filter/fhouseitems.cpp
    ../Filter/fhouseitems.h
    ../Filter/fhouseitems.ui
    ../Filter/fincompleteguestsnames.cpp
    ../Filter/fincompleteguestsnames.h
    ../Filter/fincompleteguestsnames.ui
    ../Filter/finhousedetailbalance.cpp
    ../Filter/finhousedetailbalance.h
    ../Filter/finhousedetailbalance.ui
    ../Filter/finhouseguest.cpp
    ../Filter/finhouseguest.h
    ../Filter/finhouseguest.ui
    ../Filter/finhouseguestfuture.cpp
    ../Filter/finhouseguestfuture.h
    ../Filter/finhouseguestfuture.ui
    ../Filter/finvoices.cpp
    ../Filter/finvoices.h
    ../Filter/finvoices.ui
    ../Filter/flengthofstay.cpp
    ../Filter/flengthofstay.h
    ../Filter/flengthofstay.ui
    ../Filter/flistsourcereserve.cpp
    ../Filter/flistsourcereserve.h
    ../Filter/flistsourcereserve.ui
    ../Filter/fmonthlyoccperc.cpp
    ../Filter/fmonthlyoccperc.h
    ../Filter/fmonthlyoccperc.ui
    ../Filter/fnoshowcancelationfee.cpp
    ../Filter/fnoshowcancelationfee.h
    ../Filter/fnoshowcancelationfee.ui
    ../Filter/freportbypayment.cpp
    ../Filter/freportbypayment.h
    ../Filter/freportbypayment.ui
    ../Filter/freservaionremarks.cpp
    ../Filter/freservaionremarks.h
    ../Filter/freservaionremarks.ui
    ../Filter/freservationscommon.cpp
    ../Filter/freservationscommon.h
    ../Filter/freservationscommon.ui
    ../Filter/freservebycreate.cpp
    ../Filter/freservebycreate.h
    ../Filter/freservebycreate.ui
    ../Filter/freservegroups.cpp
    ../Filter/freservegroups.h
    ../Filter/freservegroups.ui
    ../Filter/frestauranttotal.cpp
    ../Filter/frestauranttotal.h
    ../Filter/frestauranttotal.ui
    ../Filter/frestguestview.cpp
    ../Filter/frestguestview.h
    ../Filter/frestguestview.ui
    ../Filter/frestsalebystore.cpp
    ../Filter/frestsalebystore.h
    ../Filter/frestsalebystore.ui
    ../Filter/froomarrangement.cpp
    ../Filter/froomarrangement.h
    ../Filter/froomarrangement.ui
    ../Filter/froomcatsale.cpp
    ../Filter/froomcatsale.h
    ../Filter/froomcatsale.ui
    ../Filter/froomstate.cpp
    ../Filter/froomstate.h
    ../Filter/froomstate.ui
    ../Filter/froomstates.cpp
    ../Filter/froomstates.h
    ../Filter/froomstates.ui
    ../Filter/fsalary.cpp
    ../Filter/fsalary.h
    ../Filter/fsalary.ui
    ../Filter/fsalesbycar.ui
    ../Filter/fstoremovement.ui
    ../Filter/ftaxreport.cpp
    ../Filter/ftaxreport.h
    ../Filter/ftaxreport.ui
    ../Filter/ftrackchanges.cpp
    ../Filter/ftrackchanges.h
    ../Filter/ftrackchanges.ui
    ../Filter/fvauchers.cpp
    ../Filter/fvauchers.h
    ../Filter/fvauchers.ui
    ../Filter/fwakeupcall.cpp
    ../Filter/fwakeupcall.h
    ../Filter/fwakeupcall.ui
    ../Filter/fyearlyfinancialreport.cpp
    ../Filter/fyearlyfinancialreport.h
    ../Filter/fyearlyfinancialreport.ui
    ../Filter/guestcheckin.cpp
    ../Filter/guestcheckin.h
    ../Filter/guestcheckin.ui
    ../Filter/wcardexlist.cpp
    ../Filter/wcardexlist.h
    ../Filter/wcityledgerlist.cpp
    ../Filter/wcityledgerlist.h
    ../Filter/wfilterbase.cpp
    ../Filter/wfilterbase.h
)

set(SOURCES_PRINT
    ../Print/dlgprintreservation.cpp
    ../Print/dlgprintreservation.h
    ../Print/dlgprintreservation.ui
    ../Print/pdefaults.h
    ../Print/pexportinvoicetoexcel.cpp
    ../Print/pexportinvoicetoexcel.h
    ../Print/pimage.cpp
    ../Print/pimage.h
    ../Print/pprintcheckin.cpp
    ../Print/pprintcheckin.h
    ../Print/pprintheader.cpp
    ../Print/pprintheader.h
    ../Print/pprintinvoice.cpp
    ../Print/pprintinvoice.h
    ../Print/pprintpreview.cpp
    ../Print/pprintpreview.h
    ../Print/pprintpreview.ui
    ../Print/pprintreceipt.cpp
    ../Print/pprintreceipt.h
    ../Print/pprintscene.cpp
    ../Print/pprintscene.h
    ../Print/pprintstoredoc.cpp
    ../Print/pprintstoredoc.h
    ../Print/pprintstoreentry.cpp
    ../Print/pprintstoreentry.h
    ../Print/pprintvaucher.cpp
    ../Print/pprintvaucher.h
    ../Print/printtaxd.cpp
    ../Print/printtaxd.h
    ../Print/printtaxd.ui
    ../Print/ptextrect.cpp
    ../Print/ptextrect.h
)

set(SOURCES_WIDGETS
    ../Widgets/storedoc.cpp
    ../Widgets/storedoc.h
    ../Widgets/storedoc.ui
    ../Widgets/wcashentry.cpp
    ../Widgets/wcashentry.h
    ../Widgets/wcashentry.ui
    ../Widgets/wcustomreports.cpp
    ../Widgets/wcustomreports.h
    ../Widgets/wcustomreports.ui
    ../Widgets/wdate2.cpp
    ../Widgets/wdate2.h
    ../Widgets/wdate2.ui
    ../Widgets/wendofdayaciton.cpp
    ../Widgets/wendofdayaciton.h
    ../Widgets/wendofdayaciton.ui
    ../Widgets/whotelstatus.cpp
    ../Widgets/whotelstatus.h
    ../Widgets/whotelstatus.ui
    ../Widgets/wrecheckin.cpp
    ../Widgets/wrecheckin.h
    ../Widgets/wrecheckin.ui
    ../Widgets/wremarks.cpp
    ../Widgets/wremarks.h
    ../Widgets/wreportbuilder.cpp
    ../Widgets/wreportbuilder.h
    ../Widgets/wreportbuilder.ui
    ../Widgets/wreportssetold.cpp
    ../Widgets/wreportssetold.h
    ../Widgets/wreportssetold.ui
    ../Widgets/wstoreentry.cpp
    ../Widgets/wstoreentry.h
    ../Widgets/wstoreentry.ui
    ../Widgets/wvauchereditor.cpp
    ../Widgets/wvauchereditor.h
    ../Widgets/wvauchereditor.ui
    ../Widgets/wweb.cpp
    ../Widgets/wweb.h
    ../Widgets/wweb.ui
)

set(SOURCES_THREADS
    ../Threads/broadcastthread.cpp
    ../Threads/broadcastthread.h
)

set(SOURCES_RGDOUBLECLICK
    ../RGDoubleClick/rgcityledgerdetailedbalance.cpp
    ../RGDoubleClick/rgcityledgerdetailedbalance.h
    ../RGDoubleClick/rgdoubleclickdelegate.cpp
    ../RGDoubleClick/rgdoubleclickdelegate.h
)

set(SOURCES_GRIDOPTIONWIDGETS
    ../GridOptionWidgets/godaily.cpp
    ../GridOptionWidgets/godaily.h
    ../GridOptionWidgets/godaily.ui
    ../GridOptionWidgets/gowidget.cpp
    ../GridOptionWidgets/gowidget.h
)

set(SOURCES_VOUCHERS
    ../Vouchers/basevoucher.cpp
    ../Vouchers/basevoucher.h
    ../Vouchers/voucher_av.cpp
    ../Vouchers/voucher_av.h
    ../Vouchers/voucher_tc.cpp
    ../Vouchers/voucher_tc.h
)

set(SOURCES_SERVER2
    ../Server2/datahandler.cpp
    ../Server2/datahandler.h
    ../Server2/listener.cpp
    ../Server2/listener.h
    ../Server2/socketconnection.cpp
    ../Server2/socketconnection.h
)

set(PROJECT_SOURCES
    ${SOURCES_RESORT}
    ${SOURCES_BASE}
    ${SOURCES_CACHE}
    ${SOURCES_CACHE2}
    ${SOURCES_CONTROLS}
    ${SOURCES_ROWEDITOR}
    ${SOURCES_ROOMCHART}
    ${SOURCES_FILTER}
    ${SOURCES_PRINT}
    ${SOURCES_WIDGETS}
    ${SOURCES_THREADS}
    ${SOURCES_RGDOUBLECLICK}
    ${SOURCES_GRIDOPTIONWIDGETS}
    ${SOURCES_VOUCHERS}
    ${SOURCES_SERVER2}
)
